<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>COLOR</name>
   <tag></tag>
   <elementGuidId>9b0bf9eb-43e1-4d52-81b1-874d57bfaefe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rptAttribute_txtAttrContent_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rptAttribute_txtAttrContent_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>421f9e1d-8d77-460e-84c7-a581b6424575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rptAttribute$ctl00$txtAttrContent</value>
      <webElementGuid>a1389c85-cabe-4e7b-ba76-f9fae2ce9dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>72db754d-14c7-4f33-b06f-b87c11554190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>50551a17-d48d-4487-b7eb-0c22246b8d99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rptAttribute_txtAttrContent_0</value>
      <webElementGuid>823585b7-c1c4-48d6-88c0-a9c13c385895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtMedInputStyle</value>
      <webElementGuid>b40ba4ef-8e5e-48a6-8ca3-1b71016af100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rptAttribute_txtAttrContent_0&quot;)</value>
      <webElementGuid>74b3c4a8-5bcd-4e53-bb1d-d32ac099decc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Asset/iframe_Term  Condition_appForm</value>
      <webElementGuid>6dc8f319-1135-4ad8-bc1e-04c6af8bb22e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rptAttribute_txtAttrContent_0']</value>
      <webElementGuid>48d88d03-f154-4d84-91e9-ad374410e6cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dAssAttr']/table/tbody/tr/td[2]/input</value>
      <webElementGuid>68c75ded-b3a9-4a37-9fad-775b63c1469c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>e4ebc140-efc0-4fa4-b009-9b8e884b6872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'rptAttribute$ctl00$txtAttrContent' and @type = 'text' and @id = 'rptAttribute_txtAttrContent_0']</value>
      <webElementGuid>fef15789-fb9d-4010-a59b-d230bd2105a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
