<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Down Payment</name>
   <tag></tag>
   <elementGuidId>ecbb3a8c-63ab-445a-96c0-cc2b80cc3928</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucDownPayment_txtInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucDownPayment_txtInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>99b8df5e-d09c-4ee4-bad9-ee138125ed74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucDownPayment$txtInput</value>
      <webElementGuid>f36b67ad-fb83-48c5-8c12-d3fd8267c385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>57e6628d-efce-4281-915d-b52df2ed7994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>6ed734af-3788-4bd6-b550-c17a8108e27b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucDownPayment_txtInput</value>
      <webElementGuid>acc41c82-107a-400a-8030-501ea276bdee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtAmountStyle</value>
      <webElementGuid>94499f9f-79e8-4a40-9eb8-f5f8610273ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>formatValue('ucDownPayment_txtInput','ucDownPayment_hdnInput','ucDownPayment_txtInputDummy');</value>
      <webElementGuid>5e270be5-9e49-4ba1-966a-694fed987f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clearFormatValue('ucDownPayment_txtInput');</value>
      <webElementGuid>5d3dede2-2c7e-47f1-a25d-2d5e2835fad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return validateKey(event);</value>
      <webElementGuid>8cfe65f8-ee20-4d9a-bae6-b95d6dab35c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucDownPayment_txtInput&quot;)</value>
      <webElementGuid>65222b44-3f03-49d1-986e-0be858ba8c87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Asset/iframe_Term  Condition_appForm</value>
      <webElementGuid>7c6198b9-5c31-415b-8799-3fc9787c6b24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucDownPayment_txtInput']</value>
      <webElementGuid>1adbfdbb-acae-4697-a154-4da9c256a3f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dMainAss']/table/tbody/tr[7]/td[2]/input[2]</value>
      <webElementGuid>869ef0a8-cdd4-4d8d-8e80-8a2c1c7e282a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/input[2]</value>
      <webElementGuid>35146bc2-558b-48ac-9f98-a82d88ae1385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucDownPayment$txtInput' and @type = 'text' and @id = 'ucDownPayment_txtInput']</value>
      <webElementGuid>5c6f6568-1a2e-4711-aa35-2f5326f57967</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
