<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Term  Condition_appForm</name>
   <tag></tag>
   <elementGuidId>2ee67f21-bd30-4cbf-8ea8-a33f6b0284bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#appForm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='appForm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>43e86eee-2f8e-4682-a816-e666bee50c3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/CONFINS_TRAIN/LOS.X/CreditProcess/NewApplication/AssetData/AssDataX.aspx?AppId=1632006&amp;AppSrc=</value>
      <webElementGuid>390bb99d-4535-4c54-a32c-0d46229c4978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>appForm</value>
      <webElementGuid>127f0eb3-324f-4688-8b0d-ec1bee15d449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>appForm</value>
      <webElementGuid>e0dab24e-7d1a-48e3-8030-368960ffa075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2b25202c-4814-4271-8386-e5af20f30f1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appForm&quot;)</value>
      <webElementGuid>66b50b0e-294c-4439-b58a-f7d9e76fe9d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Asset/iframe_Welcome, Anita Gusti, KEDOYA, Credit Admin_mainPage</value>
      <webElementGuid>9ce18a32-61ee-4689-ad70-83de0205d35b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='appForm']</value>
      <webElementGuid>b66889bf-c2c6-44ef-b1b1-1aba4d0299c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='appFormContainer']/iframe</value>
      <webElementGuid>71acb1a6-a9b6-4c30-afe9-1b08478b85e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>3adfbbb3-46ba-4d32-89d7-c0ac6389c1be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/CONFINS_TRAIN/LOS.X/CreditProcess/NewApplication/AssetData/AssDataX.aspx?AppId=1632006&amp;AppSrc=' and @id = 'appForm' and @name = 'appForm']</value>
      <webElementGuid>9c89a8bd-26c4-4bf3-9fc9-db8d695ae003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/CONFINS_TRAIN/LOS.X/CreditProcess/NewApplication/AssetData/AssDataX.aspx?AppId=1632011&amp;AppSrc=' and @id = 'appForm' and @name = 'appForm']</value>
      <webElementGuid>d0cf3832-98f7-4880-a1ef-2bcdf60f0750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/CONFINS_TRAIN/LOS.X/CreditProcess/NewApplication/AssetData/AssDataX.aspx?AppId=1632008&amp;AppSrc=' and @id = 'appForm' and @name = 'appForm']</value>
      <webElementGuid>ccdf4000-53e0-44a5-9569-a8533de4d032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/CONFINS_TRAIN/LOS.X/CreditProcess/NewApplication/AssetData/AssDataX.aspx?AppId=1632007&amp;AppSrc=' and @id = 'appForm' and @name = 'appForm']</value>
      <webElementGuid>4509f772-5a74-4289-b874-2e03a1c97df2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/CONFINS_TRAIN/LOS.X/CreditProcess/NewApplication/AssetData/AssDataX.aspx?AppId=1632003&amp;AppSrc=' and @id = 'appForm' and @name = 'appForm']</value>
      <webElementGuid>bf9fa9b5-e71a-41f3-8b4a-8c2df06bf203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/CONFINS_TRAIN/LOS.X/CreditProcess/NewApplication/AssetData/AssDataX.aspx?AppId=1631997&amp;AppSrc=' and @id = 'appForm' and @name = 'appForm']</value>
      <webElementGuid>0742abb2-82d3-4bf4-9afb-075e1997bca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/CONFINS_TRAIN/LOS.X/CreditProcess/NewApplication/AssetData/AssDataX.aspx?AppId=1631993&amp;AppSrc=' and @id = 'appForm' and @name = 'appForm']</value>
      <webElementGuid>456a7afd-f835-4e6c-8f04-25f0f8132743</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
