<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City Name</name>
   <tag></tag>
   <elementGuidId>ec358b41-4d70-4828-842c-30b66403121b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucLookupCity_uclCity_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucLookupCity_uclCity_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a5029b9d-eba7-4ec8-945b-df2e5f857bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucLookupCity$uclCity$umd$ctl00$ucS$rptFixedSearch$ctl02$txtSearchValue</value>
      <webElementGuid>1e84bec4-dd5b-44e9-99c9-357d8227d687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dfc8f376-49e8-4180-929c-66cc0f1b81f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucLookupCity_uclCity_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_1</value>
      <webElementGuid>50f39d66-0a9a-48f0-a12d-cb5e35160b00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtInput</value>
      <webElementGuid>03d6aefa-cf10-422c-bf17-579ca7da7a80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucLookupCity_uclCity_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_1&quot;)</value>
      <webElementGuid>71378bd4-5248-4002-ac77-e74d8f0ca63a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Asset/iframe_Term  Condition_appForm</value>
      <webElementGuid>3307ec4e-10ae-4069-86f8-a96e006826c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucLookupCity_uclCity_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_1']</value>
      <webElementGuid>3636bc81-2fcb-43df-b2f0-e9d0b08423ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ucLookupCity_uclCity_umd_ctl00_ucS_upFixedSearch']/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>713cf065-fa6a-4772-990f-fdaa0e51ac13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/div/div/div/div/div/div/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>fb54ab50-9854-4f89-ac46-a51c113b43bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucLookupCity$uclCity$umd$ctl00$ucS$rptFixedSearch$ctl02$txtSearchValue' and @type = 'text' and @id = 'ucLookupCity_uclCity_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_1']</value>
      <webElementGuid>84340b34-7e02-4faa-925c-28ba0ebdba90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
