<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input Bekas</name>
   <tag></tag>
   <elementGuidId>e6cc10ec-9835-4fee-a043-8e53814ffce2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rblAssetCondition_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rblAssetCondition_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>04eb7aca-04dc-4577-86d7-874f298fc730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rblAssetCondition_1</value>
      <webElementGuid>0f324a7a-e799-4ef7-b5c3-c618dc159ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6359673e-1fd6-41cd-a7ec-b2400599a395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rblAssetCondition</value>
      <webElementGuid>6a3774ed-1f21-4114-9aaf-5fdfc58eadf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>USED</value>
      <webElementGuid>9320fd37-ff72-489f-929a-59ac991735ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'rblAssetCondition$1\',\'\')', 0)</value>
      <webElementGuid>9517b0c7-ea04-482b-9530-e68d1c7ada0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rblAssetCondition_1&quot;)</value>
      <webElementGuid>61ad323d-3c0a-4993-885c-d617b6b708c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Asset/iframe_Term  Condition_appForm</value>
      <webElementGuid>98dc5f8f-4a6d-4754-9180-00094be31714</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rblAssetCondition_1']</value>
      <webElementGuid>97542c8a-1af0-474f-b2a0-3c0049088bbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='rblAssetCondition']/tbody/tr/td[2]/input</value>
      <webElementGuid>e829f024-7c49-49be-9e0f-5a70a77c4d28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>bf847e38-8185-4fdc-ab31-3cc51d703320</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'rblAssetCondition_1' and @type = 'radio' and @name = 'rblAssetCondition']</value>
      <webElementGuid>e0deb73c-aa0c-4f49-a576-04459596ecea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
