<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input Baru</name>
   <tag></tag>
   <elementGuidId>64ef0f70-243f-4a0b-8b05-21b5262e8a17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rblAssetCondition_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rblAssetCondition_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>12aec39d-1d51-4b64-9588-1ca48f38b5be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rblAssetCondition_0</value>
      <webElementGuid>1eab0ada-f45b-42b7-b293-59073ec3ac84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>89260717-02d7-43ae-b77b-9e31b9bf5115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rblAssetCondition</value>
      <webElementGuid>9b31021f-da8a-47b8-84c4-7dfe6fe05aef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>NEW</value>
      <webElementGuid>a51b0f0b-f2b1-451b-959b-b875ae3be558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>b74e22ff-eae1-441b-8efb-f1f389f82d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rblAssetCondition_0&quot;)</value>
      <webElementGuid>62c8cb8c-aebd-4203-9675-f7fbe9b4692a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Asset/iframe_Term  Condition_appForm</value>
      <webElementGuid>d02b85cc-0587-4b8f-afe9-1cb9a0e7650a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rblAssetCondition_0']</value>
      <webElementGuid>07541d21-a549-41bb-bd13-b1df99b614b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='rblAssetCondition']/tbody/tr/td/input</value>
      <webElementGuid>e205c4b4-fa74-416f-8133-5b43523be40f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>433bb0b4-a9e8-4475-89f5-30d96d45b5ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'rblAssetCondition_0' and @type = 'radio' and @name = 'rblAssetCondition' and @checked = 'checked']</value>
      <webElementGuid>f0ff91ee-cd5a-4eb1-951c-00ad3b74438a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
