<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Asset Price</name>
   <tag></tag>
   <elementGuidId>16de9771-c7f8-4477-b26a-db635e6d56c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucAssetPrice_txtInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucAssetPrice_txtInput']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ucAssetPrice_txtInput&quot;)[count(. | //*[@name = 'ucAssetPrice$txtInput' and @type = 'text' and @id = 'ucAssetPrice_txtInput' and @ref_element = 'Object Repository/Menu/Credit admin/Page_New Confins - Main/iframe_Term  Condition_appForm']) = count(//*[@name = 'ucAssetPrice$txtInput' and @type = 'text' and @id = 'ucAssetPrice_txtInput' and @ref_element = 'Object Repository/Menu/Credit admin/Page_New Confins - Main/iframe_Term  Condition_appForm'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a215e857-bb16-4ef8-b119-e17dffc525ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucAssetPrice$txtInput</value>
      <webElementGuid>9ced5139-bf30-4052-9507-c38636ceb6bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>acf80341-3f36-424e-a282-51c50de0a38d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>9faa7c8a-b7e3-4cfc-9bd3-871c8dc7a376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucAssetPrice_txtInput</value>
      <webElementGuid>d8044b41-35b3-4d55-ba78-0172187f2c11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtAmountStyle</value>
      <webElementGuid>7f2d5604-f519-4030-8f56-8ea99b4b7408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>formatValue('ucAssetPrice_txtInput','ucAssetPrice_hdnInput','ucAssetPrice_txtInputDummy');</value>
      <webElementGuid>f05d6cbd-b3e0-499c-9fa8-771cf8207eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clearFormatValue('ucAssetPrice_txtInput');</value>
      <webElementGuid>9f960f73-c7c7-497d-85de-4138358835f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return validateKey(event);</value>
      <webElementGuid>8fc791e0-5042-4581-bc33-3ff3dcbf740b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucAssetPrice_txtInput&quot;)</value>
      <webElementGuid>39c758ba-4d8b-4fd8-bafb-44f0c85205a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Asset/iframe_Term  Condition_appForm</value>
      <webElementGuid>a7ef7029-38c3-49a4-8510-9e94555c3af3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucAssetPrice_txtInput']</value>
      <webElementGuid>99bf03ea-a04b-46dc-8831-f00c360841c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dMainAss']/table/tbody/tr[5]/td[2]/input[2]</value>
      <webElementGuid>a066fa46-178e-4298-8199-03a64145ddfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/input[2]</value>
      <webElementGuid>3c76cf9a-963c-4630-90f1-2ac65e45e2d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucAssetPrice$txtInput' and @type = 'text' and @id = 'ucAssetPrice_txtInput']</value>
      <webElementGuid>a860c6f1-7f2d-4a7f-b438-68615f884b73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
