<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LicensePlateNo</name>
   <tag></tag>
   <elementGuidId>493a5334-774b-4cad-b3fe-560ce48f034e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtLicensePlateNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtLicensePlateNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5d6149e-6c72-47ea-82c0-fcf4e7d19180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtLicensePlateNo</value>
      <webElementGuid>ea91037c-8f60-4b33-b835-3ca81c68542b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7c6a45e4-7385-449b-b631-b008a310c3cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtLicensePlateNo</value>
      <webElementGuid>ea248f59-2073-4114-aa54-863d6e055ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtMedInputStyle</value>
      <webElementGuid>123e2f93-991f-4930-bfca-9c73f216ecc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtLicensePlateNo&quot;)</value>
      <webElementGuid>03599bb8-48aa-4181-8dc6-81fbe0b14087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Asset/iframe_Term  Condition_appForm</value>
      <webElementGuid>643d9fdc-1cd1-4c96-9799-a595b40b03df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtLicensePlateNo']</value>
      <webElementGuid>efbbdbfe-bb53-41c5-a883-38381f6ec2bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='trLicensePlate']/td[2]/input</value>
      <webElementGuid>9fc1d9fd-8c0e-4724-953d-f60206ee05e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>45786c9e-4874-4efa-beea-1722820efd37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtLicensePlateNo' and @type = 'text' and @id = 'txtLicensePlateNo']</value>
      <webElementGuid>1b260bdf-b130-4753-8940-19fdce13dd71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
