<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ManufacturingYear</name>
   <tag></tag>
   <elementGuidId>04714e7b-9055-4f7b-8a95-a50d003ad1fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtManufacturingYear</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtManufacturingYear']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>176aaf5f-380e-48b8-bb63-2969a952f8a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtManufacturingYear</value>
      <webElementGuid>c457cbcf-ac30-4155-83d6-d8e30c1b58c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>47df423d-51ef-4f24-8144-9c25943876ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>e6e045cf-5689-4672-a2cd-48a4c0dc1018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'txtManufacturingYear\',\'\')', 0)</value>
      <webElementGuid>ba1d78e6-ad58-497e-8b47-66cab472fc42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (WebForm_TextBoxKeyHandler(event) == false) return false;return isNumberKey(event)</value>
      <webElementGuid>3f1c338d-d6e5-45f1-9f70-62222c19b7e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtManufacturingYear</value>
      <webElementGuid>d6496725-6aff-4bf4-9d58-600e03c80cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtMedInputStyle</value>
      <webElementGuid>485f603c-82a9-4335-ae71-5da1810a4a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtManufacturingYear&quot;)</value>
      <webElementGuid>319081ac-7634-4c61-9326-dc5a8177def4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Asset/iframe_Term  Condition_appForm</value>
      <webElementGuid>196aad0d-a3b3-4d08-8642-a687a1b3a858</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtManufacturingYear']</value>
      <webElementGuid>621c6c20-e176-4a78-974c-1c0fd9387cdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dMainAss']/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>94e41bac-945e-4984-81c9-530a5ae4850c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>83fa9a12-e195-45c4-9018-d9980b076c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtManufacturingYear' and @type = 'text' and @id = 'txtManufacturingYear']</value>
      <webElementGuid>466e8890-3501-4bf7-9a76-3728610f9e3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
