<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NO MESIN</name>
   <tag></tag>
   <elementGuidId>9956e88d-53b8-4fed-b27c-304855ce6eb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtSerialNo2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtSerialNo2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ab345780-33d7-4871-967e-18cbc43cae7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtSerialNo2</value>
      <webElementGuid>bcb13e14-c6a4-4fdb-ad7f-6ec8ffa6dd89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>20e4c0e7-e27f-489b-b877-3c003250e52c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtSerialNo2</value>
      <webElementGuid>2a8aabca-a6af-4f1c-b105-f6293c85188d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtMedInputStyle</value>
      <webElementGuid>d3f1cb70-6094-4825-af94-5a2c87685688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtSerialNo2&quot;)</value>
      <webElementGuid>f27f6db9-dce1-4184-9fc3-4071f2c7c5d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Asset/iframe_Term  Condition_appForm</value>
      <webElementGuid>0dc2f51e-709a-461a-8568-7775a53cb80d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtSerialNo2']</value>
      <webElementGuid>6fce27e5-5b12-4e0c-824b-fc1b9d7e713a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dAssetData']/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>f7764fa9-9501-4eb8-96d6-40e728e8d915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>a9b0bb6d-07ec-49b4-ba58-9ffbbcd65925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtSerialNo2' and @type = 'text' and @id = 'txtSerialNo2']</value>
      <webElementGuid>bc607431-6a21-4d50-8c3e-b7ace7bc4cbc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
