<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SEARCH Asset Name</name>
   <tag></tag>
   <elementGuidId>f89bc4fd-de4a-4634-883e-222269a1eeca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucLookupAssetSchm_uclAssetSchm_umd_ctl00_ucS_lbSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ucLookupAssetSchm_uclAssetSchm_umd_ctl00_ucS_lbSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4f5aafd5-f129-4c01-a08b-2c5616568114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucLookupAssetSchm_uclAssetSchm_umd_ctl00_ucS_lbSearch</value>
      <webElementGuid>77316e9e-52fb-4086-a09a-a6ec26e2e5dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnForm</value>
      <webElementGuid>779b5c98-6006-4407-969c-688d59633e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ucLookupAssetSchm$uclAssetSchm$umd$ctl00$ucS$lbSearch&quot;, &quot;&quot;, true, &quot;ucLookupAssetSchm_uclAssetSchm_umd_ctl00_ucS_lbSearchVldtnGrp&quot;, &quot;&quot;, false, true))</value>
      <webElementGuid>ee2ed414-3459-4db0-a62c-ca253a2e816f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SEARCH</value>
      <webElementGuid>e388e324-4437-478b-bc5d-ad05748d6e63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucLookupAssetSchm_uclAssetSchm_umd_ctl00_ucS_lbSearch&quot;)</value>
      <webElementGuid>a3426663-87df-4859-bd95-52dcda8484b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Asset/iframe_Term  Condition_appForm</value>
      <webElementGuid>f9dc9b46-c63f-446f-aa40-c00a9850df21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ucLookupAssetSchm_uclAssetSchm_umd_ctl00_ucS_lbSearch']</value>
      <webElementGuid>916bbfe0-3a20-4a6c-81b7-3d7abad51c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ucLookupAssetSchm_uclAssetSchm_umd_ctl00_ucS_upButtonSearch']/a</value>
      <webElementGuid>351ce0b2-ce58-41c8-be4d-e76a1937e22c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'SEARCH')])[2]</value>
      <webElementGuid>e346db1c-261e-40dc-8e73-edd7630787c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asset Name'])[2]/following::a[1]</value>
      <webElementGuid>09976ff6-4c22-4558-8fbc-299bf625b9dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOOK UP - Asset Lookup'])[1]/following::a[1]</value>
      <webElementGuid>7918b909-d97d-4205-9aef-cee0dd43722d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RESET'])[2]/preceding::a[1]</value>
      <webElementGuid>aeaf67d2-75f2-49b2-83f8-e955ca8d2050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asset Name'])[3]/preceding::a[2]</value>
      <webElementGuid>6711e5da-5d9b-4f86-ba21-2162c3df34e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ucLookupAssetSchm$uclAssetSchm$umd$ctl00$ucS$lbSearch&quot;, &quot;&quot;, true, &quot;ucLookupAssetSchm_uclAssetSchm_umd_ctl00_ucS_lbSearchVldtnGrp&quot;, &quot;&quot;, false, true))')]</value>
      <webElementGuid>e389eb06-b4c9-49f5-9141-f80eb69f3ada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/table/tbody/tr/td[2]/div/div/div/div/div/table/tbody/tr/td/div/a</value>
      <webElementGuid>0ed00126-49d4-4445-8653-42aa2a67e506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ucLookupAssetSchm_uclAssetSchm_umd_ctl00_ucS_lbSearch' and @href = 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ucLookupAssetSchm$uclAssetSchm$umd$ctl00$ucS$lbSearch&quot;, &quot;&quot;, true, &quot;ucLookupAssetSchm_uclAssetSchm_umd_ctl00_ucS_lbSearchVldtnGrp&quot;, &quot;&quot;, false, true))' and (text() = 'SEARCH' or . = 'SEARCH')]</value>
      <webElementGuid>b14d12c8-923b-4e51-b67e-d0c355ea459f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
