<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search</name>
   <tag></tag>
   <elementGuidId>b0cb8cbc-9900-4266-beb5-01df00fd24ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucLookupSupplBranchSchm_uclSupplBranchSchmX_imb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucLookupSupplBranchSchm_uclSupplBranchSchmX_imb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c1e69df4-a6d0-4b97-8af8-447fdb84a72b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>526e9b1e-6e82-462a-86bb-30365505b4a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucLookupSupplBranchSchm$uclSupplBranchSchmX$imb</value>
      <webElementGuid>aead362a-077c-4ba0-89ad-4aebd0c1c214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucLookupSupplBranchSchm_uclSupplBranchSchmX_imb</value>
      <webElementGuid>896a3dff-4fdf-41fa-8751-fbe9e791e3b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../../Images/Icon/IconLookup.gif</value>
      <webElementGuid>eb7af577-2375-4b2c-8cdd-8e79e00851f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>overlay('mdnucLookupSupplBranchSchm_uclSupplBranchSchmX');</value>
      <webElementGuid>15d99953-61a2-41c3-bd96-b7e03161a2d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucLookupSupplBranchSchm_uclSupplBranchSchmX_imb&quot;)</value>
      <webElementGuid>061e9dc9-a6d9-4869-b2b0-3dedd5490158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Asset/iframe_Term  Condition_appForm</value>
      <webElementGuid>8ed4e089-d27c-451a-a8db-7797d7fe58a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucLookupSupplBranchSchm_uclSupplBranchSchmX_imb']</value>
      <webElementGuid>eca3d781-6486-41e2-b0cf-3a7d540cec03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dMainSuppl']/table/tbody/tr/td[2]/ul/li/input[2]</value>
      <webElementGuid>391471ee-2030-4889-8e95-42a91a858c7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input[2]</value>
      <webElementGuid>5dc59bd3-86f4-4b70-8bdf-7b171a7a9874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ucLookupSupplBranchSchm$uclSupplBranchSchmX$imb' and @id = 'ucLookupSupplBranchSchm_uclSupplBranchSchmX_imb' and @src = '../../../../Images/Icon/IconLookup.gif']</value>
      <webElementGuid>4f10f0f0-98f4-440d-8c74-5da91fa59c4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
