<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select Asset Name</name>
   <tag></tag>
   <elementGuidId>fc12ddcc-3afb-4baf-b1eb-ed192686252e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucLookupAssetSchm_uclAssetSchm_umd_ctl00_gvL_hpSelect_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ucLookupAssetSchm_uclAssetSchm_umd_ctl00_gvL_hpSelect_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>43fd8fc6-6449-47f7-b63f-47ce03effb17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucLookupAssetSchm_uclAssetSchm_umd_ctl00_gvL_hpSelect_0</value>
      <webElementGuid>829c833f-e565-4a41-b77b-a6fbf60ae5d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:AssetSchm('ucLookupAssetSchm_uclAssetSchm_txt','ucLookupAssetSchm_uclAssetSchm_hd1','APPKTM GAJAH GAJAH 200 DP 1.8 M','ucLookupAssetSchm_uclAssetSchm_hd2','GAJAH 200 DP 1.8 M','ucLookupAssetSchm_uclAssetSchm_hd3','967','ucLookupAssetSchm_uclAssetSchm_hd4','31','ucLookupAssetSchm_uclAssetSchm_hd5','21591');;overlay('mdnucLookupAssetSchm_uclAssetSchm');__doPostBack('mdnucLookupAssetSchm_uclAssetSchm', '')</value>
      <webElementGuid>41c31001-34a4-4f8a-be9b-952d54da157f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>a21b24fd-b363-457c-843f-03102f832c87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucLookupAssetSchm_uclAssetSchm_umd_ctl00_gvL_hpSelect_0&quot;)</value>
      <webElementGuid>438d910f-f8ef-4df6-9aa5-d723e8eb67f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Asset/iframe_Term  Condition_appForm</value>
      <webElementGuid>f70ca2f4-dc2d-4e96-bd78-4343a924a494</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ucLookupAssetSchm_uclAssetSchm_umd_ctl00_gvL_hpSelect_0']</value>
      <webElementGuid>d5c378db-2574-4f8b-97e2-b806f8893fdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ucLookupAssetSchm_uclAssetSchm_umd_ctl00_gvL']/tbody/tr[2]/td[2]/a</value>
      <webElementGuid>cef971ed-6e7b-468d-be35-6ca0afea907f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Select')]</value>
      <webElementGuid>2e1b9755-af2f-4fae-b405-ef097e7aa388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APPKTM GAJAH GAJAH 200 DP 1.8 M'])[1]/following::a[1]</value>
      <webElementGuid>a0c94aac-dc1e-4425-9354-2b75cfc385fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SELECT'])[2]/following::a[1]</value>
      <webElementGuid>bb16af84-7fd7-49f6-9e6a-4f3fac426c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APRILIA SR GT 200'])[1]/preceding::a[1]</value>
      <webElementGuid>a7a71bf5-2bd3-418f-8b35-879bef9418db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select'])[2]/preceding::a[1]</value>
      <webElementGuid>21a330be-785d-498a-845f-e07ca7b458c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
      <webElementGuid>9df92185-6e22-40d2-9bd5-f8df3e29cc5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:AssetSchm('ucLookupAssetSchm_uclAssetSchm_txt','ucLookupAssetSchm_uclAssetSchm_hd1','APPKTM GAJAH GAJAH 200 DP 1.8 M','ucLookupAssetSchm_uclAssetSchm_hd2','GAJAH 200 DP 1.8 M','ucLookupAssetSchm_uclAssetSchm_hd3','967','ucLookupAssetSchm_uclAssetSchm_hd4','31','ucLookupAssetSchm_uclAssetSchm_hd5','21591');;overlay('mdnucLookupAssetSchm_uclAssetSchm');__doPostBack('mdnucLookupAssetSchm_uclAssetSchm', '')&quot;)]</value>
      <webElementGuid>468fada9-50ee-4a78-b831-b5b8d829febe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>de8fd475-3a1b-4a43-b1fa-628bcfd4036f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ucLookupAssetSchm_uclAssetSchm_umd_ctl00_gvL_hpSelect_0' and @href = concat(&quot;javascript:AssetSchm(&quot; , &quot;'&quot; , &quot;ucLookupAssetSchm_uclAssetSchm_txt&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupAssetSchm_uclAssetSchm_hd1&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;APPKTM GAJAH GAJAH 200 DP 1.8 M&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupAssetSchm_uclAssetSchm_hd2&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;GAJAH 200 DP 1.8 M&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupAssetSchm_uclAssetSchm_hd3&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;967&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupAssetSchm_uclAssetSchm_hd4&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;31&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupAssetSchm_uclAssetSchm_hd5&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;21591&quot; , &quot;'&quot; , &quot;);;overlay(&quot; , &quot;'&quot; , &quot;mdnucLookupAssetSchm_uclAssetSchm&quot; , &quot;'&quot; , &quot;);__doPostBack(&quot; , &quot;'&quot; , &quot;mdnucLookupAssetSchm_uclAssetSchm&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>668785ba-1a2c-4e31-8d80-9887464a4965</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
