<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select Nama Supplier</name>
   <tag></tag>
   <elementGuidId>373755b7-ef38-45bd-af01-ebc788108ac5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucLookupSupplBranchSchm_uclSupplBranchSchmX_umd_ctl00_gvL_hpSelect_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ucLookupSupplBranchSchm_uclSupplBranchSchmX_umd_ctl00_gvL_hpSelect_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d8a4b91d-909b-44c4-83c2-ef72e4966c8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucLookupSupplBranchSchm_uclSupplBranchSchmX_umd_ctl00_gvL_hpSelect_0</value>
      <webElementGuid>c5758ba7-34b4-4a3d-ad10-7aa985aaf6b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:SupplBranchSchmLookupX('ucLookupSupplBranchSchm_uclSupplBranchSchmX_txt','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd1',' ARTHA JAYA MOBILINDO','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd2','3','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd3','17585','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd4','ARTHA JAYA MOBILINDO','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd5','NORMAL','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd6','JL RAYA AL BARKAH NO 9','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd7','6/7/2024 12:00:00 AM');;overlay('mdnucLookupSupplBranchSchm_uclSupplBranchSchmX');__doPostBack('mdnucLookupSupplBranchSchm_uclSupplBranchSchmX', '')</value>
      <webElementGuid>c5164b94-b05a-4079-9130-289f341b209b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>d91f9cc4-e921-4ab0-a1f9-d0f8cf7add0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucLookupSupplBranchSchm_uclSupplBranchSchmX_umd_ctl00_gvL_hpSelect_0&quot;)</value>
      <webElementGuid>5844127c-7265-44c9-aabc-2208f689bb75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Asset/iframe_Term  Condition_appForm</value>
      <webElementGuid>d63a4ada-8fbb-41a1-9387-5085ee2b98b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ucLookupSupplBranchSchm_uclSupplBranchSchmX_umd_ctl00_gvL_hpSelect_0']</value>
      <webElementGuid>4390ea64-4f2c-47d8-b9db-0529e23ebef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ucLookupSupplBranchSchm_uclSupplBranchSchmX_umd_ctl00_gvL']/tbody/tr[2]/td[6]/a</value>
      <webElementGuid>a63b3c3e-2de6-417d-bb51-d3aa3eaf2fa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Select')]</value>
      <webElementGuid>226b4cb3-e0a1-4399-836e-485a60a31e68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JL RAYA AL BARKAH NO 9'])[1]/following::a[1]</value>
      <webElementGuid>ae987f4e-a7fa-4555-a681-43add1d547cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NORMAL'])[2]/following::a[1]</value>
      <webElementGuid>e4cbdc28-d68b-4bed-b753-3b9436d345ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AUTO HAUS'])[1]/preceding::a[1]</value>
      <webElementGuid>9c870814-187e-4536-9cbc-198bb7308ad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AUTO HAUS'])[2]/preceding::a[1]</value>
      <webElementGuid>496b81ea-bb3f-460f-b66a-64e39081bd3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
      <webElementGuid>343dcd58-9396-42ad-bfcb-db004d4b767f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:SupplBranchSchmLookupX('ucLookupSupplBranchSchm_uclSupplBranchSchmX_txt','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd1',' ARTHA JAYA MOBILINDO','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd2','3','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd3','17585','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd4','ARTHA JAYA MOBILINDO','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd5','NORMAL','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd6','JL RAYA AL BARKAH NO 9','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd7','6/7/2024 12:00:00 AM');;overlay('mdnucLookupSupplBranchSchm_uclSupplBranchSchmX');__doPostBack('mdnucLookupSupplBranchSchm_uclSupplBranchSchmX', '')&quot;)]</value>
      <webElementGuid>af564b04-ad1f-4259-b809-3ef7b4d2c900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/a</value>
      <webElementGuid>78105cd3-13c6-4c11-86f4-125c5dfcc746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ucLookupSupplBranchSchm_uclSupplBranchSchmX_umd_ctl00_gvL_hpSelect_0' and @href = concat(&quot;javascript:SupplBranchSchmLookupX(&quot; , &quot;'&quot; , &quot;ucLookupSupplBranchSchm_uclSupplBranchSchmX_txt&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd1&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot; ARTHA JAYA MOBILINDO&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd2&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;3&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd3&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;17585&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd4&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ARTHA JAYA MOBILINDO&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd5&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;NORMAL&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd6&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;JL RAYA AL BARKAH NO 9&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd7&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;6/7/2024 12:00:00 AM&quot; , &quot;'&quot; , &quot;);;overlay(&quot; , &quot;'&quot; , &quot;mdnucLookupSupplBranchSchm_uclSupplBranchSchmX&quot; , &quot;'&quot; , &quot;);__doPostBack(&quot; , &quot;'&quot; , &quot;mdnucLookupSupplBranchSchm_uclSupplBranchSchmX&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>1cfba628-cb8a-4055-a758-36f3ca89bbcd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
