<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select City Name</name>
   <tag></tag>
   <elementGuidId>2a2f42e3-4e96-4610-a574-286e638b6ce6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucLookupCity_uclCity_umd_ctl00_gvL_hpSelect_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ucLookupCity_uclCity_umd_ctl00_gvL_hpSelect_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8eab1be8-b451-4c18-8720-3d04bd90a001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucLookupCity_uclCity_umd_ctl00_gvL_hpSelect_0</value>
      <webElementGuid>6869b710-1b91-4707-bdd7-7b6159d914ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:CityLookup('ucLookupCity_uclCity_hd1','0393','ucLookupCity_uclCity_hd2','3465','ucLookupCity_uclCity_txt','ucLookupCity_uclCity_hd3','Jakarta Barat, Wil. Kota');;overlay('mdnucLookupCity_uclCity');__doPostBack('mdnucLookupCity_uclCity', '')</value>
      <webElementGuid>83efa6ee-d229-4a45-bc02-2d1ab7070006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>f94ca7d5-36f2-43c6-8fe2-238fe712b6f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucLookupCity_uclCity_umd_ctl00_gvL_hpSelect_0&quot;)</value>
      <webElementGuid>30e81ca5-6f0f-41b4-9563-7083176ad144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Asset/iframe_Term  Condition_appForm</value>
      <webElementGuid>0322922e-3534-416b-a167-80d5c796ebc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ucLookupCity_uclCity_umd_ctl00_gvL_hpSelect_0']</value>
      <webElementGuid>d0683017-dd0e-40ba-a0ff-ccc7d2494f5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ucLookupCity_uclCity_umd_ctl00_gvL']/tbody/tr[2]/td[3]/a</value>
      <webElementGuid>4ce59226-e562-4c76-acd3-a2dc06086c4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Select')]</value>
      <webElementGuid>1c783777-2ceb-42ae-9aef-7e4127890524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jakarta Barat, Wil. Kota'])[1]/following::a[1]</value>
      <webElementGuid>53bf8bff-ad3f-494a-afee-23517575281d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SELECT'])[1]/following::a[1]</value>
      <webElementGuid>a518ff60-3bb7-4f2e-934b-e6c3a09e0a8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|&lt;'])[1]/preceding::a[1]</value>
      <webElementGuid>4a481da8-c433-4c5c-8701-9691f2428a5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
      <webElementGuid>e5a1458d-cdf9-4c77-9690-d60755a3ebfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:CityLookup('ucLookupCity_uclCity_hd1','0393','ucLookupCity_uclCity_hd2','3465','ucLookupCity_uclCity_txt','ucLookupCity_uclCity_hd3','Jakarta Barat, Wil. Kota');;overlay('mdnucLookupCity_uclCity');__doPostBack('mdnucLookupCity_uclCity', '')&quot;)]</value>
      <webElementGuid>fe319c3c-973a-401a-967d-010b30f1d35a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
      <webElementGuid>974d1333-755b-4d11-bd4c-ee3f11c7c7d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ucLookupCity_uclCity_umd_ctl00_gvL_hpSelect_0' and @href = concat(&quot;javascript:CityLookup(&quot; , &quot;'&quot; , &quot;ucLookupCity_uclCity_hd1&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;0393&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupCity_uclCity_hd2&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;3465&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupCity_uclCity_txt&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupCity_uclCity_hd3&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;Jakarta Barat, Wil. Kota&quot; , &quot;'&quot; , &quot;);;overlay(&quot; , &quot;'&quot; , &quot;mdnucLookupCity_uclCity&quot; , &quot;'&quot; , &quot;);__doPostBack(&quot; , &quot;'&quot; , &quot;mdnucLookupCity_uclCity&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>aabd9e6c-758b-473b-9dd7-dff511ef55c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
