<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Self usage</name>
   <tag></tag>
   <elementGuidId>64e09541-f9d5-4ffb-b12a-2b06918318b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbSelfUsage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cbSelfUsage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5262ec82-bf40-4207-ac40-4cf5250c2596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbSelfUsage</value>
      <webElementGuid>0b5506db-1a6e-4f31-ad4b-62153dd6ec6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7d49d438-da7d-4161-bbf9-d90d5866ef39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cbSelfUsage</value>
      <webElementGuid>27527710-d625-4dae-a1a7-7af7009f213a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'cbSelfUsage\',\'\')', 0)</value>
      <webElementGuid>65746561-6434-4e23-a6e2-ab7c4c168f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbSelfUsage&quot;)</value>
      <webElementGuid>3fb848fd-7f19-47b2-947c-2470e324fada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Asset/iframe_Term  Condition_appForm</value>
      <webElementGuid>74a02dc6-0075-4ba9-8b06-c314e8dc583b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cbSelfUsage']</value>
      <webElementGuid>84518323-858a-442f-ae93-e2c7d6cd6cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dAssUser']/table/tbody/tr/td[2]/input</value>
      <webElementGuid>b167790d-f218-4e44-8d07-066791d76dd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2fc22e15-24dd-4bf2-b290-78548ba99f8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cbSelfUsage' and @type = 'checkbox' and @name = 'cbSelfUsage']</value>
      <webElementGuid>e1518515-bc7f-4947-94bc-080221880a3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
