<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TaxDate</name>
   <tag></tag>
   <elementGuidId>4f57b738-5152-42a6-8b4f-26240830658d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucTaxDate_txtDatePicker</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucTaxDate_txtDatePicker']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b36523e0-39fe-4818-8711-bc20df7ba691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucTaxDate$txtDatePicker</value>
      <webElementGuid>c3cc8738-9c55-4b9e-9954-a6624027a16f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e4973f35-9f6d-4ca2-86a7-4a35249632f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucTaxDate_txtDatePicker</value>
      <webElementGuid>ad39c929-262d-494b-a7f0-2048b74245c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datePicker hasDatepicker</value>
      <webElementGuid>439587cf-487b-4f1d-9be8-8bc792bc21aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>copy('ucTaxDate_txtDatePicker','ucTaxDate_txtHidden', 'ucTaxDate_rvDate')</value>
      <webElementGuid>e01718e9-218c-4700-9eab-25d93320650c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucTaxDate_txtDatePicker&quot;)</value>
      <webElementGuid>961d0701-61e1-4a48-b751-e19839e81668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Asset/iframe_Term  Condition_appForm</value>
      <webElementGuid>656f5054-c442-4144-9d58-289965e537ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucTaxDate_txtDatePicker']</value>
      <webElementGuid>bab200ee-aeac-4b89-a308-2694b48f87ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dAssOwner']/table[2]/tbody/tr/td[2]/input</value>
      <webElementGuid>bfc75f9e-2699-4311-9f9a-9b0850fa1d71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td[2]/input</value>
      <webElementGuid>1a037e28-f67b-4ee6-96bc-45060f7c0bbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucTaxDate$txtDatePicker' and @type = 'text' and @id = 'ucTaxDate_txtDatePicker']</value>
      <webElementGuid>ad7640fc-6cf6-494f-9a24-c7cf2d730ad5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
