<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Fiducia Yes</name>
   <tag></tag>
   <elementGuidId>b13646b9-9d5f-4333-b4c3-7d46e45a2677</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rblIsFudiciaCovered_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rblIsFudiciaCovered_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd061913-9fcd-44c9-b157-48c089aafd8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rblIsFudiciaCovered_0</value>
      <webElementGuid>f4200558-97d9-452d-a945-2e26f2177522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>202a10d8-fef0-48dc-8585-01331c3bf2d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rblIsFudiciaCovered</value>
      <webElementGuid>112fd02b-90db-4f50-8bc0-cd4b3013c0a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>34063ce7-92fc-45ea-b0b1-32ec5bddc8af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rblIsFudiciaCovered_0&quot;)</value>
      <webElementGuid>dbc77120-a742-48e9-8729-a1a55887ba7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Application/iframe_Term  Condition_appForm</value>
      <webElementGuid>4340bc4e-8095-4791-ad1b-be344f07a399</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rblIsFudiciaCovered_0']</value>
      <webElementGuid>04f31149-eb1a-4074-883e-6cad83bee38e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='rblIsFudiciaCovered']/tbody/tr/td/input</value>
      <webElementGuid>539234ed-cc6f-4eeb-a43f-32e9ee4f7693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>f7afb693-d559-4c2c-9f69-4afb06f16cb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'rblIsFudiciaCovered_0' and @type = 'radio' and @name = 'rblIsFudiciaCovered']</value>
      <webElementGuid>5d1596a0-afe4-4cfa-97a6-dc5c56702c1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
