<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Fudicia No</name>
   <tag></tag>
   <elementGuidId>d83e4ed9-14fb-49c5-bf3c-6546d7e2d81b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rblIsFudiciaCovered_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rblIsFudiciaCovered_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac6ee8d7-8356-4a8b-b263-9b33e82a73c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rblIsFudiciaCovered_1</value>
      <webElementGuid>fb5b501d-e7f8-481b-810e-c77146875884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>39b84059-439f-4148-a907-297aceca63d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rblIsFudiciaCovered</value>
      <webElementGuid>32f95304-8d0b-4327-abc9-0dcf5b447436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>09a7eced-287e-4ca9-a696-0c3ee4186603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>2e23f108-da7d-42d6-80aa-0c970ae7f0fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rblIsFudiciaCovered_1&quot;)</value>
      <webElementGuid>5c6ae5e0-2f86-4530-9a4f-cc97a224ddbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Application/iframe_Term  Condition_appForm</value>
      <webElementGuid>edcfec5b-b50e-4e9f-9950-af4e67a3217a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rblIsFudiciaCovered_1']</value>
      <webElementGuid>709fed33-50b7-4e32-a0ee-80f88f381a2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='rblIsFudiciaCovered']/tbody/tr/td[2]/input</value>
      <webElementGuid>41d104f6-0715-471f-b875-48000a9f2a19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>b1da448a-adec-44d6-bacc-85bb1e767754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'rblIsFudiciaCovered_1' and @type = 'radio' and @name = 'rblIsFudiciaCovered' and @checked = 'checked']</value>
      <webElementGuid>971a41cd-e172-4415-9ce9-5b3638d8230f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
