<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Installment Type Arrear</name>
   <tag></tag>
   <elementGuidId>23281e02-a6b2-4c55-8ca4-0549ed2ac204</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rblFirstInstType_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rblFirstInstType_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5cb6f4bd-e64a-415a-830c-de1452cbeeb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rblFirstInstType_1</value>
      <webElementGuid>b3161e1d-b752-46dc-b88b-31ef0b965c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>27ce7883-7c24-403d-9053-d13db483373f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rblFirstInstType</value>
      <webElementGuid>a9d35fe4-ab47-4c60-9d0a-18fdf721ef69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>AR</value>
      <webElementGuid>598d5e9c-28d0-4b08-a5e0-c712da34d2c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rblFirstInstType_1&quot;)</value>
      <webElementGuid>b63e5b69-bf34-422a-a223-5aa476f68671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Application/iframe_Term  Condition_appForm</value>
      <webElementGuid>fbd7abd1-e789-4115-88b5-2ce885cc8810</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rblFirstInstType_1']</value>
      <webElementGuid>4ab845b7-10ad-4d6f-a777-770c387a4547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='rblFirstInstType']/tbody/tr/td[2]/input</value>
      <webElementGuid>23311707-bb6d-4b91-8345-d2c63032dcfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>6d699b5b-76b7-4dca-b7d5-8216b0da7e42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'rblFirstInstType_1' and @type = 'radio' and @name = 'rblFirstInstType']</value>
      <webElementGuid>5d7680e4-06ce-476a-ac8d-2a65a3376b2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
