<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NTF Asset</name>
   <tag></tag>
   <elementGuidId>823ae708-e9cc-4339-9f26-d1c9d9622acb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rblMrFiduciaCalcMethod_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rblMrFiduciaCalcMethod_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b40c64d-ced0-4bf7-950e-563eb828f06a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rblMrFiduciaCalcMethod_1</value>
      <webElementGuid>996e3278-2f67-43ec-a120-ccf5d218f299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>03d081c6-7a48-4ff6-af3f-b94195dfd41a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rblMrFiduciaCalcMethod</value>
      <webElementGuid>4181a732-7ee4-459b-89ac-fa6c0dd31ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>FIDUCIA_NTF_ASSET</value>
      <webElementGuid>051a1887-0332-4f90-9d72-a238a80496a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>92e03a84-3a8c-440b-adc8-3dffdea12de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rblMrFiduciaCalcMethod_1&quot;)</value>
      <webElementGuid>74d2294d-d2ea-4dfd-bbfc-f0327cc103f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Application/iframe_Term  Condition_appForm</value>
      <webElementGuid>26a7896e-cb9c-4a0a-8b10-bbfdf88809d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rblMrFiduciaCalcMethod_1']</value>
      <webElementGuid>0b8c9362-7a90-4bce-88c4-d30ea2560326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='rblMrFiduciaCalcMethod']/tbody/tr/td[2]/input</value>
      <webElementGuid>77e80cae-6bbc-437e-8342-34e4bd5fa190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>666d19b4-2350-477a-8737-8ad8b43a780f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'rblMrFiduciaCalcMethod_1' and @type = 'radio' and @name = 'rblMrFiduciaCalcMethod' and @checked = 'checked']</value>
      <webElementGuid>c885354d-ca4e-42aa-94ac-cd5659e3420b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
