<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NTF Agreement</name>
   <tag></tag>
   <elementGuidId>7f22f337-684e-4a27-9433-ae4a76d46f06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rblMrFiduciaCalcMethod_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rblMrFiduciaCalcMethod_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7df541d1-0055-4565-b306-91f723e13ea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rblMrFiduciaCalcMethod_0</value>
      <webElementGuid>f9d7c37f-b043-410b-aa16-1c89270a4fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>495a4703-7d61-40c6-abd8-0202ccaa551c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rblMrFiduciaCalcMethod</value>
      <webElementGuid>f05d137a-62ce-4197-a9bf-4dcb82f1df89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>FIDUCIA_NTF_AGRMNT</value>
      <webElementGuid>4e9c2e05-1601-44f0-a2c3-6dbd8a02aa58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rblMrFiduciaCalcMethod_0&quot;)</value>
      <webElementGuid>9b01bc57-9b34-455f-8b9d-e7a0b9cf8124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Application/iframe_Term  Condition_appForm</value>
      <webElementGuid>5871c716-9894-4fc0-86f4-d32fa62ad087</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rblMrFiduciaCalcMethod_0']</value>
      <webElementGuid>2151f197-2a14-449c-9b80-189c03f3e70d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='rblMrFiduciaCalcMethod']/tbody/tr/td/input</value>
      <webElementGuid>d0c089c8-1e55-4581-8bc5-60b7bbb4dc74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>931a66c1-189c-490a-9fbb-b77e052e362e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'rblMrFiduciaCalcMethod_0' and @type = 'radio' and @name = 'rblMrFiduciaCalcMethod']</value>
      <webElementGuid>c48b6cb9-31b5-4e28-aa1f-5ee1f5472529</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
