<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SaveCont Application data</name>
   <tag></tag>
   <elementGuidId>024eb7ca-5422-4664-b595-5d6542e66ab3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lb_Form_SaveCont']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lb_Form_SaveCont</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'lb_Form_SaveCont' and @ref_element = 'Object Repository/Menu/Credit admin/Page_New Confins - Main/iframe_Term  Condition_appForm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c96a74a2-4f37-4b05-86cb-79865abbe4ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>400829d1-b6a0-4fcc-84fc-c1f7ee2c6b7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lb_Form_SaveCont</value>
      <webElementGuid>54e2f9c8-edee-45ff-bd4c-c869134d5e19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save &amp; Continue</value>
      <webElementGuid>b667134a-f570-4be3-a758-a8182302c695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;lb_Form_SaveCont&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, false))</value>
      <webElementGuid>5e3c726b-e04d-4c56-8b68-64b477ab6a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lb_Form_SaveCont</value>
      <webElementGuid>cffcd14e-c0ac-4d93-8b2d-0e557a5bad46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnForm</value>
      <webElementGuid>a643c360-d4eb-419d-8472-ea4fc4f4df3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lb_Form_SaveCont&quot;)</value>
      <webElementGuid>21dbd4c1-ed44-4765-82e4-9b4ca3d00f95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Application/iframe_Term  Condition_appForm</value>
      <webElementGuid>7dd915ed-0ec0-4442-9975-5e183a0c0115</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lb_Form_SaveCont']</value>
      <webElementGuid>bea8cde3-4053-49e7-8feb-01048b7ef55f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='btnFormContainer']/input</value>
      <webElementGuid>c4e023d0-86c6-4826-9b59-ee7fcbdc48d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/input</value>
      <webElementGuid>4ed69463-7898-4568-a04a-e8ed92179115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'lb_Form_SaveCont' and @id = 'lb_Form_SaveCont']</value>
      <webElementGuid>6e496b3b-500c-47ed-a8ab-cd2df7cafc94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
