<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Coverage Amountt</name>
   <tag></tag>
   <elementGuidId>888fbb25-4233-401b-a69a-d612f0b5d9d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucInsInit_ucINInsCvgAmt_txtInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucInsInit_ucINInsCvgAmt_txtInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2b67d0d-cb5e-4ea4-ad3a-1c79edec4e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucInsInit$ucINInsCvgAmt$txtInput</value>
      <webElementGuid>ef034460-3b0a-4b0b-850f-0dcd4ed1d726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>94c28c87-dbec-4672-af31-63617b829cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>a01aa8f1-c449-408d-a113-3d8ef06e4798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucInsInit_ucINInsCvgAmt_txtInput</value>
      <webElementGuid>1fc65833-f5aa-41d7-a9da-ecd723103ef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtAmountStyle</value>
      <webElementGuid>a821dbdb-9222-4c0c-a830-64d10289abe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>formatValue('ucInsInit_ucINInsCvgAmt_txtInput','ucInsInit_ucINInsCvgAmt_hdnInput','ucInsInit_ucINInsCvgAmt_txtInputDummy');</value>
      <webElementGuid>f0366362-7711-4e9f-8969-796c6032a828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clearFormatValue('ucInsInit_ucINInsCvgAmt_txtInput');</value>
      <webElementGuid>2826009d-2da9-46e0-b888-ade555d116c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return validateKey(event);</value>
      <webElementGuid>af52075d-49b4-4f0c-97cb-c7c4524b9fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucInsInit_ucINInsCvgAmt_txtInput&quot;)</value>
      <webElementGuid>e6c54646-45df-477b-bb37-b35ee28ac122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Insurance Asset/iframe_Term  Condition_appForm</value>
      <webElementGuid>89b4fee2-160d-4864-8a8d-54caa7cc0b2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucInsInit_ucINInsCvgAmt_txtInput']</value>
      <webElementGuid>f303754b-c5d6-4e4e-8ec7-c35be1354dc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ucInsInit_dInsInitCust']/table/tbody/tr[3]/td[4]/input[2]</value>
      <webElementGuid>7e2720cc-ccff-49fb-8cf9-fb022d782bfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/input[2]</value>
      <webElementGuid>c0dbfa81-ab3d-4dc0-bb9c-f6e7215b605a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucInsInit$ucINInsCvgAmt$txtInput' and @type = 'text' and @id = 'ucInsInit_ucINInsCvgAmt_txtInput']</value>
      <webElementGuid>c008d97b-dffb-4fa1-b437-795c8b61a7c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
