<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit INS</name>
   <tag></tag>
   <elementGuidId>6a09c44d-725e-4a3b-a31c-d43768bd6618</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvEntryIns_imbEdit_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvEntryIns_imbEdit_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>953d2db3-0f32-4097-add8-8e2fa542bc0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>d5fd2ac3-595e-49e5-8f74-d3368101b026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvEntryIns$ctl02$imbEdit</value>
      <webElementGuid>c5812380-2416-499d-b6f6-f2f9de7092d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvEntryIns_imbEdit_0</value>
      <webElementGuid>590a87a5-3e43-4c3d-9eb7-62b0fb0e5f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Edit Record</value>
      <webElementGuid>96e9cf89-a518-449e-bc9a-6230bca3087b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../../Images/Edit.gif</value>
      <webElementGuid>d2a6010e-956c-484d-838a-2f2a3db4c917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvEntryIns_imbEdit_0&quot;)</value>
      <webElementGuid>f1394e37-65a9-4709-869e-daae259103ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Insurance Asset/iframe_Term  Condition_appForm (1)</value>
      <webElementGuid>9c697afb-2ecf-4d6f-9099-8d8507e6a32a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvEntryIns_imbEdit_0']</value>
      <webElementGuid>2a76a608-b2c9-47a7-87b3-15e3e05c8a1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvEntryIns']/tbody/tr[2]/td[10]/input</value>
      <webElementGuid>030478b8-2054-4a90-88e4-11297d8af6c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[10]/input</value>
      <webElementGuid>aa1080a0-e9f6-4ddf-b090-2714cf0ad0f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'gvEntryIns$ctl02$imbEdit' and @id = 'gvEntryIns_imbEdit_0' and @title = 'Edit Record' and @src = '../../../../Images/Edit.gif']</value>
      <webElementGuid>8a0b82f5-1f58-4f84-abcc-ce19c8e8be6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
