<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>End Date</name>
   <tag></tag>
   <elementGuidId>11b2124c-f710-44e5-a2cc-ea380bdb263a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucInsInit_ucDPCustCoverEndDt_txtDatePicker</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucInsInit_ucDPCustCoverEndDt_txtDatePicker']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>44560d61-2486-4269-9ce2-b444e202d4ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucInsInit$ucDPCustCoverEndDt$txtDatePicker</value>
      <webElementGuid>6c644665-66a1-4595-88d8-59ffe68bd1e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>55d75480-bffd-42e1-86c4-3702a6b5ac32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>copy('ucInsInit_ucDPCustCoverEndDt_txtDatePicker','ucInsInit_ucDPCustCoverEndDt_txtHidden', 'ucInsInit_ucDPCustCoverEndDt_rvDate');setTimeout('__doPostBack(\'ucInsInit$ucDPCustCoverEndDt$txtDatePicker\',\'\')', 0)</value>
      <webElementGuid>87027ccc-81f3-4c71-83ab-88de2180b335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (WebForm_TextBoxKeyHandler(event) == false) return false;</value>
      <webElementGuid>784d3d2b-f095-4e21-b26d-d8d4a73c8ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucInsInit_ucDPCustCoverEndDt_txtDatePicker</value>
      <webElementGuid>f43a970f-9601-445b-a62e-6f35ca628c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datePicker hasDatepicker</value>
      <webElementGuid>4598c66f-4a23-4f82-9fca-16983cccce75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucInsInit_ucDPCustCoverEndDt_txtDatePicker&quot;)</value>
      <webElementGuid>6aa82ae7-30e6-46f2-9e7c-03ad08c39219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Insurance Asset/iframe_Term  Condition_appForm</value>
      <webElementGuid>93498c23-142c-40ed-95b8-0e1cc3908936</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucInsInit_ucDPCustCoverEndDt_txtDatePicker']</value>
      <webElementGuid>538e4d06-8f18-4ace-85b8-cf1a5181ea77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ucInsInit_dInsInitCust']/table/tbody/tr[4]/td[4]/input</value>
      <webElementGuid>80221a3f-0fa8-4735-b70e-db0e6fdf7a27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[4]/input</value>
      <webElementGuid>8e7991ec-818a-496c-b5cc-c0c9ebf806f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucInsInit$ucDPCustCoverEndDt$txtDatePicker' and @type = 'text' and @id = 'ucInsInit_ucDPCustCoverEndDt_txtDatePicker']</value>
      <webElementGuid>055b35f1-da81-4411-be83-9a1cd63d83a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
