<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Insco Branch Name</name>
   <tag></tag>
   <elementGuidId>08f8032c-96bf-46fd-bc49-091611a46c26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucInsInit_txtInscoBranchNameInsInitCust</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucInsInit_txtInscoBranchNameInsInitCust']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b7314edb-7bda-4323-8cde-81f027e7ffc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucInsInit$txtInscoBranchNameInsInitCust</value>
      <webElementGuid>34292738-e1f1-4296-9c3a-f6e4d8ee0efd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bdaa611f-606c-4311-8319-317bf51458c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucInsInit_txtInscoBranchNameInsInitCust</value>
      <webElementGuid>5498393a-ad70-48c4-955b-611e6d15a068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtMedInputStyle</value>
      <webElementGuid>69373ed2-2144-48e3-ad6f-75d7a8d78b27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucInsInit_txtInscoBranchNameInsInitCust&quot;)</value>
      <webElementGuid>247ee4f4-de96-4b95-acc2-4e7bd5735d84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Insurance Asset/iframe_Term  Condition_appForm</value>
      <webElementGuid>7c90b922-7866-4ada-860d-873af458e2a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucInsInit_txtInscoBranchNameInsInitCust']</value>
      <webElementGuid>8a918c4a-68ad-4994-a664-0a5ebed938fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ucInsInit_dInsInitCust']/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>236eedd1-2e3d-4ae0-9838-a50de4977b91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>d82a33f9-c70a-4797-a269-2175879c7ac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucInsInit$txtInscoBranchNameInsInitCust' and @type = 'text' and @id = 'ucInsInit_txtInscoBranchNameInsInitCust']</value>
      <webElementGuid>89b3051b-5cab-4448-a293-695e0face834</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
