<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Insurance Length</name>
   <tag></tag>
   <elementGuidId>d9b0c2fd-aecd-4a6a-aa9d-75ab90240580</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucInsInit_ucINInsLength_txtInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucInsInit_ucINInsLength_txtInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fac56a6d-6808-4936-bf0e-850ea7f59402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucInsInit$ucINInsLength$txtInput</value>
      <webElementGuid>eaf2db04-9530-4b12-94ab-fc270e127ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>daae5f07-23e4-4d16-a99e-a6f1c1815f1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>e92c9523-0371-47d4-bfa6-21e612aca9e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucInsInit_ucINInsLength_txtInput</value>
      <webElementGuid>f54fcf39-53c1-40d7-bef4-2da2a2098bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>11bfd8d6-34a9-4874-be33-1cf27a21dd87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aspNetDisabled txtMedPercentageStyle</value>
      <webElementGuid>0ad9f397-8b3c-491e-8ea5-4426de60d1aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>formatValueInteger('ucInsInit_ucINInsLength_txtInput','ucInsInit_ucINInsLength_hdnInput','ucInsInit_ucINInsLength_txtInputDummy');</value>
      <webElementGuid>5abdde88-4816-4df8-bdca-53e16d751850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clearFormatValue('ucInsInit_ucINInsLength_txtInput');</value>
      <webElementGuid>d2b84244-6ab1-4e56-aa9e-8899eac3c233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return validateKey(event);</value>
      <webElementGuid>8f594467-60b9-49e3-8b23-9125f2bc0386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucInsInit_ucINInsLength_txtInput&quot;)</value>
      <webElementGuid>fadac0e9-e59b-4d14-9dfe-6ccec9cb92f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Insurance Asset/iframe_Term  Condition_appForm</value>
      <webElementGuid>d3159a15-18bc-435e-9eee-71a82361993b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucInsInit_ucINInsLength_txtInput']</value>
      <webElementGuid>cc5a2e1b-3380-42d1-bdd7-cf45fbd36ad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ucInsInit_dInsInitCompany']/table/tbody/tr[4]/td[4]/input[2]</value>
      <webElementGuid>3c1ad940-a894-40c3-9610-f92cdab708b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>e7edbaef-d932-481b-9b8f-8b528896f51c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucInsInit$ucINInsLength$txtInput' and @type = 'text' and @id = 'ucInsInit_ucINInsLength_txtInput']</value>
      <webElementGuid>474b706c-1919-449a-8725-dd26dd15823d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
