<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PAID BY At Cost</name>
   <tag></tag>
   <elementGuidId>b8ff2ee8-6d93-4c68-bb97-a894e3d28552</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucInsInit_rblInsAssetPaidBy_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucInsInit_rblInsAssetPaidBy_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e588ef31-c6ae-475b-a63f-55546fc85c60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucInsInit_rblInsAssetPaidBy_1</value>
      <webElementGuid>0719ec56-a8e1-4cec-b02e-835cda9865cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>0e61e71f-cfb8-409f-8591-3a2f9edc6cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucInsInit$rblInsAssetPaidBy</value>
      <webElementGuid>e90b5d98-a505-4076-8880-2be6d95d4791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>AC</value>
      <webElementGuid>049e17b2-2d63-435b-816a-bfb4b123a2f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucInsInit_rblInsAssetPaidBy_1&quot;)</value>
      <webElementGuid>267d1448-a77d-4620-931c-af50f13d99f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Insurance Asset/iframe_Term  Condition_appForm</value>
      <webElementGuid>b6f1190f-a5d3-45c8-84bb-082dd2201ff8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucInsInit_rblInsAssetPaidBy_1']</value>
      <webElementGuid>7c795828-ec69-443b-ae6d-7d41e375674f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ucInsInit_rblInsAssetPaidBy']/tbody/tr/td[2]/input</value>
      <webElementGuid>b59cc438-f2eb-43d4-8943-c8fbd5530706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>92b6d1d6-64c5-4023-ba00-2b5d0f270759</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ucInsInit_rblInsAssetPaidBy_1' and @type = 'radio' and @name = 'ucInsInit$rblInsAssetPaidBy']</value>
      <webElementGuid>20f10722-e260-47e5-935a-79e87ca9c0cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
