<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Save</name>
   <tag></tag>
   <elementGuidId>de00d8c4-459e-4cd0-bc35-1585c55b6553</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lb_Toolbar_Save</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='lb_Toolbar_Save']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ee348ecf-b7a6-49cb-8063-a717b9bf5644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lb_Toolbar_Save</value>
      <webElementGuid>effe91f1-bc22-4b18-82e5-72916021ebcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnForm</value>
      <webElementGuid>491027b4-7236-45dc-9df3-a75419471d52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;lb_Toolbar_Save&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, true))</value>
      <webElementGuid>b40552b0-a89c-4a9d-bf5c-8ba73e9134dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>1c19a41c-4bf7-4b7a-a2e7-f807e48361a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lb_Toolbar_Save&quot;)</value>
      <webElementGuid>79452dea-7f4a-4c18-8859-645bcb7ce879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Insurance Asset/iframe_Term  Condition_appForm</value>
      <webElementGuid>fd510445-735e-44a6-a130-76c89e5c849a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='lb_Toolbar_Save']</value>
      <webElementGuid>6e359e82-3008-4199-a7df-29bfce0a643d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='upToolbar']/div/a</value>
      <webElementGuid>ac449dbc-70f1-4aa0-8fbf-d68932c3780d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Save')]</value>
      <webElementGuid>22062262-0f20-4782-95be-4cb29e28e376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::a[1]</value>
      <webElementGuid>fe718048-8668-4042-b268-c4be239a5cdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[-]'])[1]/preceding::a[2]</value>
      <webElementGuid>4ea7a992-4226-474f-8bd1-eca8532ba5d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>999e1e8e-9937-4c2e-8578-c40c94c6fcc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;lb_Toolbar_Save&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, true))')]</value>
      <webElementGuid>f6851c29-0853-4fbf-9487-de1488931c1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>1133942b-2ff6-4e02-9c0b-02adc8938c81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'lb_Toolbar_Save' and @href = 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;lb_Toolbar_Save&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, true))' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>8c21fb51-d6fc-4aa4-83d9-f8767374e8df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
