<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Start Date</name>
   <tag></tag>
   <elementGuidId>a82322ca-1cfa-4e66-b8be-ae4ed5f86b4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucInsInit_ucDPCustCoverStartDt_txtDatePicker']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ucInsInit_ucDPCustCoverStartDt_txtDatePicker</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'ucInsInit_ucDPCustCoverStartDt_txtDatePicker' and @ref_element = 'Object Repository/Menu/Credit admin/Page_New Confins - Main/iframe_Term  Condition_appForm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6ecef071-c867-412a-b214-32df2ab75290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucInsInit$ucDPCustCoverStartDt$txtDatePicker</value>
      <webElementGuid>d71175f2-5a00-4fb9-a31f-0d8aa48fac88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8f8fdd04-b2ac-4db5-9721-91db358e4b3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>copy('ucInsInit_ucDPCustCoverStartDt_txtDatePicker','ucInsInit_ucDPCustCoverStartDt_txtHidden', 'ucInsInit_ucDPCustCoverStartDt_rvDate');setTimeout('__doPostBack(\'ucInsInit$ucDPCustCoverStartDt$txtDatePicker\',\'\')', 0)</value>
      <webElementGuid>b45c2646-8690-4a1d-bada-7080e8c972b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (WebForm_TextBoxKeyHandler(event) == false) return false;</value>
      <webElementGuid>15933cbe-e9eb-4158-9ad9-07723a197e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucInsInit_ucDPCustCoverStartDt_txtDatePicker</value>
      <webElementGuid>c8a18e9f-e3db-4280-b2b2-666b5844880d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datePicker hasDatepicker</value>
      <webElementGuid>d48df5fd-a612-4762-a6e7-92224a8fbf49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucInsInit_ucDPCustCoverStartDt_txtDatePicker&quot;)</value>
      <webElementGuid>bf06e97a-1e4c-4fec-9045-878399484e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Insurance Asset/iframe_Term  Condition_appForm</value>
      <webElementGuid>3e1b1394-cb12-4147-b9a7-f95b4c7fb8c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucInsInit_ucDPCustCoverStartDt_txtDatePicker']</value>
      <webElementGuid>c5ac75ae-c9b2-48f1-98c1-f2ec097d07f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ucInsInit_dInsInitCust']/table/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>495220ed-1e54-4c94-8779-d8b7cce0304f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/input</value>
      <webElementGuid>2b1310b4-7937-4a35-972d-bdfde1f69319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucInsInit$ucDPCustCoverStartDt$txtDatePicker' and @type = 'text' and @id = 'ucInsInit_ucDPCustCoverStartDt_txtDatePicker']</value>
      <webElementGuid>9c5dc6ee-2903-4ec4-afa5-b45118c33704</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
