<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Del Supplier branch employee</name>
   <tag></tag>
   <elementGuidId>a3e9882d-0fb7-4920-963c-c3b6203c9203</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvSupplEmpCommission_ibDelSupplEmp_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gvSupplEmpCommission_ibDelSupplEmp_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gvSupplEmpCommission_ibDelSupplEmp_0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e5438c0f-b3ff-48f2-808c-7460fc128863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>1947ed5e-653a-43e6-84be-f754c6992622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvSupplEmpCommission$ctl02$ibDelSupplEmp</value>
      <webElementGuid>39275509-571e-451c-a389-324f423a63cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvSupplEmpCommission_ibDelSupplEmp_0</value>
      <webElementGuid>05053ced-1887-40ac-9b56-d5ddb5707332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Delete Record</value>
      <webElementGuid>6d8b7331-edeb-4536-94b3-122e6292bb94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../../Images/Delete.gif</value>
      <webElementGuid>2e1eaceb-c48e-4d01-b93e-23f1eedef986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return confirm('Are you sure want to delete this record');</value>
      <webElementGuid>41bea7e2-ba54-49a0-a884-86ff5aee7a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvSupplEmpCommission_ibDelSupplEmp_0&quot;)</value>
      <webElementGuid>7a85081a-01e7-48be-b7cf-c8e6cd6875f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Commision data/iframe_Term  Condition_appForm</value>
      <webElementGuid>bcca1faf-b0ba-464d-932d-9587dc763061</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvSupplEmpCommission_ibDelSupplEmp_0']</value>
      <webElementGuid>ca420004-fcd0-41c4-82e9-ee9dbbbbe505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvSupplEmpCommission']/tbody/tr[2]/td[10]/input</value>
      <webElementGuid>af73f60f-065c-42a3-836c-b1103c08999b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[10]/input</value>
      <webElementGuid>ceeff9f5-53a5-4e69-8d38-852b429eec6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'gvSupplEmpCommission$ctl02$ibDelSupplEmp' and @id = 'gvSupplEmpCommission_ibDelSupplEmp_0' and @title = 'Delete Record' and @src = '../../../../Images/Delete.gif']</value>
      <webElementGuid>507de7cd-7ace-4740-953f-4d97c8a713f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
