<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Del Supplier Commision</name>
   <tag></tag>
   <elementGuidId>62903ed0-0a83-42dc-af0e-5efa031720f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvSupplCommission_ibDelSuppl_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gvSupplCommission_ibDelSuppl_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gvSupplCommission_ibDelSuppl_0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b002c1eb-ce04-4f94-ba61-9060861da5bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>812de38b-5fec-4406-8a1e-ea52ab4274c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvSupplCommission$ctl02$ibDelSuppl</value>
      <webElementGuid>8aada192-3da1-4744-ba2f-683fe3793768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvSupplCommission_ibDelSuppl_0</value>
      <webElementGuid>413b4573-a5f4-4855-a56e-a2ce58d1e94a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Delete Record</value>
      <webElementGuid>3bbfc453-dd76-4e46-83aa-55b78b8cc13e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../../Images/Delete.gif</value>
      <webElementGuid>2f504a73-697c-4ee3-b440-17bfb07745b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return confirm('Are you sure want to delete this record');</value>
      <webElementGuid>ddac2e3b-8af5-46e5-b4ac-b510697cf917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvSupplCommission_ibDelSuppl_0&quot;)</value>
      <webElementGuid>db8c89cc-ad80-45a9-b8ae-0bd3b08614e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Commision data/iframe_Term  Condition_appForm</value>
      <webElementGuid>d5e3e1ae-b1ed-4e9f-8486-4fab28ab0970</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvSupplCommission_ibDelSuppl_0']</value>
      <webElementGuid>1d1e5778-cedb-4393-9bce-9959f5bce537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvSupplCommission']/tbody/tr[2]/td[9]/input</value>
      <webElementGuid>eefbe725-c890-41f2-b706-9976e5f82602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/input</value>
      <webElementGuid>c52cdd97-4ced-4647-bbd0-87c915ec8f1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'gvSupplCommission$ctl02$ibDelSuppl' and @id = 'gvSupplCommission_ibDelSuppl_0' and @title = 'Delete Record' and @src = '../../../../Images/Delete.gif']</value>
      <webElementGuid>a3d8c8f2-cb64-4311-b307-d74511aa78cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
