<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Incentivet</name>
   <tag></tag>
   <elementGuidId>668809d6-c56b-4853-94df-75721814262f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvSupplCommission_ucinRefundFromIncentive_0_txtInput_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gvSupplCommission_ucinRefundFromIncentive_0_txtInput_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gvSupplCommission_ucinRefundFromIncentive_0_txtInput_0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a8a43219-740a-465e-bd67-cad9e1044d3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvSupplCommission$ctl02$ucinRefundFromIncentive$txtInput</value>
      <webElementGuid>2d613523-a488-49a3-9bae-f1563d8b6a14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>01f57e68-864c-4e7d-b934-cca628f9f75f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3000000.00</value>
      <webElementGuid>b8118201-a782-4666-945c-d40039a6541c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'gvSupplCommission$ctl02$ucinRefundFromIncentive$txtInput\',\'\')', 0)</value>
      <webElementGuid>05ac6224-49b6-4748-be69-9f9088b7d79e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (WebForm_TextBoxKeyHandler(event) == false) return false;return validateKey(event);</value>
      <webElementGuid>6eadcd14-784d-4bf3-956b-e05172e9b759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvSupplCommission_ucinRefundFromIncentive_0_txtInput_0</value>
      <webElementGuid>04a0b37c-a52f-4d45-a7c9-72e2d18b3ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtAmountStyle</value>
      <webElementGuid>3bf7c8fd-2da0-4d80-a185-f3022eecdb17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>formatValue('gvSupplCommission_ucinRefundFromIncentive_0_txtInput_0','gvSupplCommission_ucinRefundFromIncentive_0_hdnInput_0','gvSupplCommission_ucinRefundFromIncentive_0_txtInputDummy_0');</value>
      <webElementGuid>f75992f6-469f-46a4-8711-6e1c61f80d64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clearFormatValue('gvSupplCommission_ucinRefundFromIncentive_0_txtInput_0');</value>
      <webElementGuid>55911af2-c456-4e16-8e5b-45bb32d16254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvSupplCommission_ucinRefundFromIncentive_0_txtInput_0&quot;)</value>
      <webElementGuid>cf42fb11-1855-46b4-b9df-d6d6f97fe8b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Commision data/iframe_Term  Condition_appForm</value>
      <webElementGuid>5f25d43e-3eb3-4140-b7a1-18fb78f63057</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvSupplCommission_ucinRefundFromIncentive_0_txtInput_0']</value>
      <webElementGuid>ab8dbeff-9e30-4f6e-a4ec-3afc325b5990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvSupplCommission']/tbody/tr[2]/td[3]/input[2]</value>
      <webElementGuid>0ea109aa-9332-4571-8f9d-ff28af9ebce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input[2]</value>
      <webElementGuid>fb8e2ed1-eb09-49fe-8fa2-14e57f198059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'gvSupplCommission$ctl02$ucinRefundFromIncentive$txtInput' and @type = 'text' and @id = 'gvSupplCommission_ucinRefundFromIncentive_0_txtInput_0']</value>
      <webElementGuid>38331e26-4986-455e-b559-07dbfef5501c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
