<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Refund</name>
   <tag></tag>
   <elementGuidId>f4ec066e-61df-4d95-8113-e19d63d9fb79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvSupplCommission_ucinRefundFromRefundSuppl_0_txtInput_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gvSupplCommission_ucinRefundFromRefundSuppl_0_txtInput_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gvSupplCommission_ucinRefundFromRefundSuppl_0_txtInput_0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f2620d97-31c8-4df0-8f39-682516f69ad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvSupplCommission$ctl02$ucinRefundFromRefundSuppl$txtInput</value>
      <webElementGuid>7b136723-00b5-4144-a4e9-f3284ce38fc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d4fa5718-fd51-4d3e-afe4-f45a78e26536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3000000.00</value>
      <webElementGuid>c3e81588-b677-43b3-936c-cd1b859112ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'gvSupplCommission$ctl02$ucinRefundFromRefundSuppl$txtInput\',\'\')', 0)</value>
      <webElementGuid>a7b8af5b-9f0a-4811-b1d0-f966fc48a0cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (WebForm_TextBoxKeyHandler(event) == false) return false;return validateKey(event);</value>
      <webElementGuid>215658b1-7098-4c66-bf3a-d654edfd8580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvSupplCommission_ucinRefundFromRefundSuppl_0_txtInput_0</value>
      <webElementGuid>ff67c980-4b8e-42c1-92e2-4a47d3d5e0ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtAmountStyle</value>
      <webElementGuid>69f2708f-e9b6-4866-918a-faab8ce34d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>formatValue('gvSupplCommission_ucinRefundFromRefundSuppl_0_txtInput_0','gvSupplCommission_ucinRefundFromRefundSuppl_0_hdnInput_0','gvSupplCommission_ucinRefundFromRefundSuppl_0_txtInputDummy_0');</value>
      <webElementGuid>4888afef-1aa3-4cd2-bd05-d1509ed1a4b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clearFormatValue('gvSupplCommission_ucinRefundFromRefundSuppl_0_txtInput_0');</value>
      <webElementGuid>d3213317-94e9-47ff-9312-5c9664656aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvSupplCommission_ucinRefundFromRefundSuppl_0_txtInput_0&quot;)</value>
      <webElementGuid>21147b3f-859a-4756-bd45-6e2d8ce7ebb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Commision data/iframe_Term  Condition_appForm</value>
      <webElementGuid>162cec97-55b6-4dfb-a30d-c4853756def6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvSupplCommission_ucinRefundFromRefundSuppl_0_txtInput_0']</value>
      <webElementGuid>7f9c2e88-71b8-4758-93b2-e485c7eaac65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvSupplCommission']/tbody/tr[2]/td[2]/input[2]</value>
      <webElementGuid>c9675f0b-28be-4815-b8d9-a06587efaa11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input[2]</value>
      <webElementGuid>dc83e136-4a7c-4d39-bd7d-955d237d48b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'gvSupplCommission$ctl02$ucinRefundFromRefundSuppl$txtInput' and @type = 'text' and @id = 'gvSupplCommission_ucinRefundFromRefundSuppl_0_txtInput_0']</value>
      <webElementGuid>2f3ce47f-527b-4265-bda5-0fda24612bfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
