<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SalesExp</name>
   <tag></tag>
   <elementGuidId>b4a077cf-461c-407a-979a-920952436ff5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvSupplCommission_ucinRefundFromSalesExp_0_txtInput_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gvSupplCommission_ucinRefundFromSalesExp_0_txtInput_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gvSupplCommission_ucinRefundFromSalesExp_0_txtInput_0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>14661251-b111-4a7f-a418-d6b304028886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvSupplCommission$ctl02$ucinRefundFromSalesExp$txtInput</value>
      <webElementGuid>f7bc9b90-86fe-4351-a622-4f5957860642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1a0f912c-a66a-4cbd-8410-610afb5c195c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3000000.00</value>
      <webElementGuid>4ef4abf6-6648-4647-aea4-bdd0e9912765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'gvSupplCommission$ctl02$ucinRefundFromSalesExp$txtInput\',\'\')', 0)</value>
      <webElementGuid>fc33057b-e6ba-4f41-ad54-7db0be75b6dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (WebForm_TextBoxKeyHandler(event) == false) return false;return validateKey(event);</value>
      <webElementGuid>672d8ee7-ffa2-4d74-bfce-911b3310478f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvSupplCommission_ucinRefundFromSalesExp_0_txtInput_0</value>
      <webElementGuid>4954136f-2157-4538-9ea6-c642667d4ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtAmountStyle</value>
      <webElementGuid>6af4f366-0b11-4b47-ae23-4099d48963f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>formatValue('gvSupplCommission_ucinRefundFromSalesExp_0_txtInput_0','gvSupplCommission_ucinRefundFromSalesExp_0_hdnInput_0','gvSupplCommission_ucinRefundFromSalesExp_0_txtInputDummy_0');</value>
      <webElementGuid>52cf5996-e071-42be-ab1e-998dfc42ae06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clearFormatValue('gvSupplCommission_ucinRefundFromSalesExp_0_txtInput_0');</value>
      <webElementGuid>f3b16acc-f028-4c41-af5f-ba8a2f92eb2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvSupplCommission_ucinRefundFromSalesExp_0_txtInput_0&quot;)</value>
      <webElementGuid>c71a6e57-2f5f-4fc9-b510-8c028857fed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Commision data/iframe_Term  Condition_appForm</value>
      <webElementGuid>79834d82-0ab7-461e-b580-36a5da8d0fa8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvSupplCommission_ucinRefundFromSalesExp_0_txtInput_0']</value>
      <webElementGuid>3b3e9ac8-aa6f-40b7-b180-1e063269758c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvSupplCommission']/tbody/tr[2]/td[4]/input[2]</value>
      <webElementGuid>3064679a-4693-4871-873e-f429ce3b36cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/input[2]</value>
      <webElementGuid>7fa824d6-48d1-4b7e-b804-871d648ba36c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'gvSupplCommission$ctl02$ucinRefundFromSalesExp$txtInput' and @type = 'text' and @id = 'gvSupplCommission_ucinRefundFromSalesExp_0_txtInput_0']</value>
      <webElementGuid>e68cbe02-53c2-4c47-83ed-acc4eade513c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
