<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CEK NO 15</name>
   <tag></tag>
   <elementGuidId>2368ae3f-4421-411b-8547-ceabb30909aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvTermCondition_cbChecked_14</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvTermCondition_cbChecked_14']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gvTermCondition_cbChecked_14</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6115d194-b13e-4740-b02d-6a24b96e749f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvTermCondition_cbChecked_14</value>
      <webElementGuid>3794454a-c713-4bce-bcbe-5354d97aa988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>688b5869-51d9-4962-a1f2-eb379f4de77e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvTermCondition$ctl16$cbChecked</value>
      <webElementGuid>21b8da05-00b6-45ef-8032-fbd5657b6cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'gvTermCondition$ctl16$cbChecked\',\'\')', 0)</value>
      <webElementGuid>adb4670e-7113-47d9-93f9-58e1599eb13c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvTermCondition_cbChecked_14&quot;)</value>
      <webElementGuid>c856f3ed-a978-4e50-8215-ded7602d9555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Term and condition/Page_New Confins - Main/iframe_Term  Condition_appForm</value>
      <webElementGuid>a6de3c9e-abc1-486d-af3c-0e482b0606ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvTermCondition_cbChecked_14']</value>
      <webElementGuid>ef14dfb1-351d-4b30-9438-944918c3251a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvTermCondition']/tbody/tr[16]/td[5]/input</value>
      <webElementGuid>b36ca506-5990-438f-89af-daa817d99cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[16]/td[5]/input</value>
      <webElementGuid>451b83f0-3038-44cd-9de9-a749a1c7e7c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'gvTermCondition_cbChecked_14' and @type = 'checkbox' and @name = 'gvTermCondition$ctl16$cbChecked']</value>
      <webElementGuid>29788d62-2ffe-4419-82f8-182887a06c01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
