<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CEK NO 27</name>
   <tag></tag>
   <elementGuidId>e9365ae2-0c15-4db9-8c2e-1402e8bf59bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvTermCondition_cbChecked_26</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvTermCondition_cbChecked_26']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gvTermCondition_cbChecked_26</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>998e9453-dfa3-460e-b279-f683ea3d9d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvTermCondition_cbChecked_26</value>
      <webElementGuid>1438d46d-740a-4f89-a84e-b2b0ba987d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7571a288-4ad9-42be-bed1-ca734fe11922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvTermCondition$ctl28$cbChecked</value>
      <webElementGuid>45ea3c55-9bab-4adb-9508-8c36e7a014b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'gvTermCondition$ctl28$cbChecked\',\'\')', 0)</value>
      <webElementGuid>69f92ae1-5596-4f55-a415-3333b752667b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvTermCondition_cbChecked_26&quot;)</value>
      <webElementGuid>5f7844cb-83e4-4af8-8cb4-604d3cb12424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Term and condition/Page_New Confins - Main/iframe_Term  Condition_appForm</value>
      <webElementGuid>e5ac3db0-03bd-430f-928e-74960fb05cf9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvTermCondition_cbChecked_26']</value>
      <webElementGuid>0bcdb4b9-43b5-4345-82da-d41613e93a48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvTermCondition']/tbody/tr[28]/td[5]/input</value>
      <webElementGuid>df51e6b6-efa3-4840-a2da-c4051e4e0e19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[28]/td[5]/input</value>
      <webElementGuid>9c73b5e7-e84c-4e27-a75c-860fc2fa66fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'gvTermCondition_cbChecked_26' and @type = 'checkbox' and @name = 'gvTermCondition$ctl28$cbChecked']</value>
      <webElementGuid>cdb5f75e-1537-4605-9a3c-8b335ead37e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
