<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CEK NO 19</name>
   <tag></tag>
   <elementGuidId>6acd27bc-ece8-4517-9c39-2ed7ec2cf771</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvTermCondition_cbChecked_18</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvTermCondition_cbChecked_18']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gvTermCondition_cbChecked_18</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b522b364-90c1-4ea5-895b-ab630b9b56c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvTermCondition_cbChecked_18</value>
      <webElementGuid>c1d19db2-82b0-4900-94cf-ad91cc56b20a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>65482019-4ae7-4775-a72d-4e5f67f2fd4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvTermCondition$ctl20$cbChecked</value>
      <webElementGuid>ff2f8fed-62e8-4552-9bcb-67294741c016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'gvTermCondition$ctl20$cbChecked\',\'\')', 0)</value>
      <webElementGuid>da96ef3f-ce17-486d-b694-a0d033bd11c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvTermCondition_cbChecked_18&quot;)</value>
      <webElementGuid>3f09a339-a517-4484-b084-000268830926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Term and condition/Page_New Confins - Main/iframe_Term  Condition_appForm</value>
      <webElementGuid>595e77d3-1896-4eff-8eab-84076f534a83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvTermCondition_cbChecked_18']</value>
      <webElementGuid>5b1adcf0-df92-4b6c-a60a-e29d6eed8b74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvTermCondition']/tbody/tr[20]/td[5]/input</value>
      <webElementGuid>82cd6f6b-c6b7-4cc9-9afb-35897dc9ee6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[20]/td[5]/input</value>
      <webElementGuid>07b9ee1a-3d7d-4838-9f90-85ad6d98950e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'gvTermCondition_cbChecked_18' and @type = 'checkbox' and @name = 'gvTermCondition$ctl20$cbChecked']</value>
      <webElementGuid>04bd1c82-9471-440e-a7ac-22d5256d4f43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
