<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NO 20</name>
   <tag></tag>
   <elementGuidId>e55326a3-9777-43cc-b1c4-c87dabdd24de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvTermCondition_lblIsMandatory_19</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='gvTermCondition_lblIsMandatory_19']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gvTermCondition_lblIsMandatory_19</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>894c6d56-9d55-4529-8a55-1aecb462bf06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvTermCondition_lblIsMandatory_19</value>
      <webElementGuid>a0028df3-dc15-4c71-b141-53eeb9ce312f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>e64a8a82-b31d-428c-8db3-b5c932506857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvTermCondition_lblIsMandatory_19&quot;)</value>
      <webElementGuid>2ca0e349-2356-4ec4-84a7-94f0514a5082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Term and condition/Page_New Confins - Main/iframe_Term  Condition_appForm</value>
      <webElementGuid>12b8d1e0-ff7c-40cc-8d2e-a36cd42a3b64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='gvTermCondition_lblIsMandatory_19']</value>
      <webElementGuid>aaa23115-eac1-4af5-81b5-12b9d94cf6b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvTermCondition']/tbody/tr[21]/td[4]/span</value>
      <webElementGuid>8b108e2f-03a4-4501-a180-975d38c8db2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GLV'])[4]/following::span[1]</value>
      <webElementGuid>9e997aa1-6e78-4305-aaef-5632cf629456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BLANKO KWITANSI A/N BPKB'])[1]/following::span[2]</value>
      <webElementGuid>887cbcd4-6f99-4929-bf74-db084f3cb752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invalid Date'])[39]/preceding::span[2]</value>
      <webElementGuid>a4ffbcb6-e04b-409b-b126-c1f8d001c373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This field is required'])[39]/preceding::span[3]</value>
      <webElementGuid>733dbc1d-d26c-4a40-82e5-8b393b4ab370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[21]/td[4]/span</value>
      <webElementGuid>bf3ebfcb-6f33-4e0c-afa1-ea49ffe343ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'gvTermCondition_lblIsMandatory_19' and (text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>b6f77c58-dab9-4bf7-861e-3edadfb49738</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
