<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NO 22</name>
   <tag></tag>
   <elementGuidId>482b9fa6-faec-4e4e-8b2a-f54bf260bafd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvTermCondition_lblIsMandatory_21</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='gvTermCondition_lblIsMandatory_21']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gvTermCondition_lblIsMandatory_21</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7b9bd91c-20a5-4264-af9a-98d43e2d22f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvTermCondition_lblIsMandatory_21</value>
      <webElementGuid>0a3cf232-b816-4b3a-ad21-575ab20cdf4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>8359de22-8af3-4a84-8c2f-fb303efb14ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvTermCondition_lblIsMandatory_21&quot;)</value>
      <webElementGuid>4a009dd6-7a2f-4676-8289-7d19dfee6735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Term and condition/Page_New Confins - Main/iframe_Term  Condition_appForm</value>
      <webElementGuid>f30c721c-8e33-4b8f-b2bc-df492799a98b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='gvTermCondition_lblIsMandatory_21']</value>
      <webElementGuid>9ef6ccf0-d4bc-4af1-babb-252f19c558b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvTermCondition']/tbody/tr[23]/td[4]/span</value>
      <webElementGuid>78c853c9-d8c3-42d5-a8b9-084f7a2f868e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GLV'])[6]/following::span[1]</value>
      <webElementGuid>90a01e4c-4175-459e-a7e5-39791a239a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TEMBUSAN FAKTUR ASLI'])[1]/following::span[2]</value>
      <webElementGuid>ca1cd5da-a14f-42b3-9de0-ffeda9c6abfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invalid Date'])[43]/preceding::span[2]</value>
      <webElementGuid>6d55ee58-6a6d-4f63-9f69-5f7e1fe3b0fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This field is required'])[43]/preceding::span[3]</value>
      <webElementGuid>032be7bd-1a76-4137-ba99-510506c214b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[23]/td[4]/span</value>
      <webElementGuid>68beefab-3a82-41d9-9d5b-1b70767b9d16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'gvTermCondition_lblIsMandatory_21' and (text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>dab5f5db-1485-44d3-815d-b48a488e3dc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
