<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CEK NO 5</name>
   <tag></tag>
   <elementGuidId>7eaddcd4-fe47-4bdb-9364-296942658f2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvTermCondition_cbChecked_4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gvTermCondition_cbChecked_4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gvTermCondition_cbChecked_4</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9002ea56-22d6-49a3-ab88-f3e0b671d19d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvTermCondition_cbChecked_4</value>
      <webElementGuid>d1847e59-1de1-46e7-8c9b-22cf8f311b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f1dab5d4-ca8e-43d8-ad9e-319c72919b21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvTermCondition$ctl06$cbChecked</value>
      <webElementGuid>3763437d-9034-4e3a-8355-ef4209e63044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'gvTermCondition$ctl06$cbChecked\',\'\')', 0)</value>
      <webElementGuid>b976f5d2-367d-48c6-bd3b-5897b17aaf0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvTermCondition_cbChecked_4&quot;)</value>
      <webElementGuid>0ad58005-a6a0-4ee0-8ef0-c18a49b5085c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Term and condition/iframe_Term  Condition_appForm</value>
      <webElementGuid>6d405b2c-4491-423a-803b-4908ac630828</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvTermCondition_cbChecked_4']</value>
      <webElementGuid>eb6f33e5-ec7b-4c87-88d9-c581ec21273b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvTermCondition']/tbody/tr[6]/td[5]/input</value>
      <webElementGuid>ac826812-1732-424a-9b47-07902c530c18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[5]/input</value>
      <webElementGuid>c4770267-a32d-486d-97db-af88bee40722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'gvTermCondition_cbChecked_4' and @type = 'checkbox' and @name = 'gvTermCondition$ctl06$cbChecked']</value>
      <webElementGuid>d7241a85-d38d-4a6f-9f8e-34fb103240e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
