<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Period Full Tenor</name>
   <tag></tag>
   <elementGuidId>1995a572-89a7-40d1-aa37-85d963332297</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucInsInit_rblInsAssetCoverPeriod_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucInsInit_rblInsAssetCoverPeriod_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ac9ae34-22d1-45bb-8dc7-be2154502293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucInsInit_rblInsAssetCoverPeriod_1</value>
      <webElementGuid>877c26fa-365a-4bd3-9c06-e8b156652ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c1ef46cf-8269-422a-875e-2c25645b4dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucInsInit$rblInsAssetCoverPeriod</value>
      <webElementGuid>e7ccf078-0a15-44f8-ba60-8d5a634d5f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>FT</value>
      <webElementGuid>048a9963-4307-40a8-9acf-065e5a099454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>6223b198-41b8-4c9e-ac6f-5b0f41613dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucInsInit_rblInsAssetCoverPeriod_1&quot;)</value>
      <webElementGuid>be991d98-5799-4e75-b253-bf0b3293fe5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Insurance Asset/iframe_Term  Condition_appForm (1)</value>
      <webElementGuid>383238fb-4d6b-42fc-b354-ce778450cd47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucInsInit_rblInsAssetCoverPeriod_1']</value>
      <webElementGuid>f56ff870-c152-46f5-afc2-781cb4d9b078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ucInsInit_rblInsAssetCoverPeriod']/tbody/tr/td[2]/input</value>
      <webElementGuid>069ad642-a29c-4879-b2bb-deba0e381626</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>4709988a-f3fd-4b0a-960f-c750095587bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ucInsInit_rblInsAssetCoverPeriod_1' and @type = 'radio' and @name = 'ucInsInit$rblInsAssetCoverPeriod' and @checked = 'checked']</value>
      <webElementGuid>d7b5fe76-5718-4363-99d0-cff25f0dbe19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
