<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Period Partial</name>
   <tag></tag>
   <elementGuidId>69abe512-d63a-482e-970c-57d77362ba0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucInsInit_rblInsAssetCoverPeriod_3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucInsInit_rblInsAssetCoverPeriod_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13aa46ef-7c97-4538-b1df-34fa798bac03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucInsInit_rblInsAssetCoverPeriod_3</value>
      <webElementGuid>ebc165ca-a7df-41ab-9fc7-c138b09134b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ac1296e9-836e-4890-a184-3a9ad942a685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucInsInit$rblInsAssetCoverPeriod</value>
      <webElementGuid>f2eafd35-bfd6-40f4-9866-bf31380f411f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>PT</value>
      <webElementGuid>7b823576-9049-4bff-a335-86b67751a4ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ucInsInit$rblInsAssetCoverPeriod$3\',\'\')', 0)</value>
      <webElementGuid>dfab91f4-90ce-41d9-84d1-e1f3e4f06c10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucInsInit_rblInsAssetCoverPeriod_3&quot;)</value>
      <webElementGuid>5d04d2a0-f334-48b6-ad60-7bec219be112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Insurance Asset/iframe_Term  Condition_appForm (1)</value>
      <webElementGuid>184d83d5-cf89-4b0c-b328-9922af730ea3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucInsInit_rblInsAssetCoverPeriod_3']</value>
      <webElementGuid>61bf2b36-58a0-48ed-99ec-c7fced8cd99c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ucInsInit_rblInsAssetCoverPeriod']/tbody/tr/td[4]/input</value>
      <webElementGuid>7cb689c3-fb61-4c08-880b-d19087c06877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/table/tbody/tr/td[4]/input</value>
      <webElementGuid>4d37c400-6188-4b9a-9006-09e85dc27935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ucInsInit_rblInsAssetCoverPeriod_3' and @type = 'radio' and @name = 'ucInsInit$rblInsAssetCoverPeriod']</value>
      <webElementGuid>aff83fab-7056-4dd4-9611-51ff75ea467c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
