<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Asset Financed</name>
   <tag></tag>
   <elementGuidId>7c1b72d9-526e-4e55-900f-84ccfab4ca1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='rptAttribute_txtAttrContent_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rptAttribute_txtAttrContent_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#rptAttribute_txtAttrContent_1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>901feeed-9991-459e-842d-439ed9c6f004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rptAttribute$ctl01$txtAttrContent</value>
      <webElementGuid>efe7c793-20eb-4a3c-9045-a360212e6235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>1d2a9870-0b95-4549-aadb-91b2b3abf2bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>49addd5b-79e6-4a15-9448-6494335801dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rptAttribute_txtAttrContent_1</value>
      <webElementGuid>6da9943a-a7f9-461c-bb06-360fbafb0fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtNotesStyle</value>
      <webElementGuid>591cbcf0-19ac-4811-9bbd-84465403b7fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rptAttribute_txtAttrContent_1&quot;)</value>
      <webElementGuid>00783991-1532-468d-a349-75b7b14f95d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Other Data/iframe_Term  Condition_appForm</value>
      <webElementGuid>e0a31059-42c9-412b-8987-1d84cd407b4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='rptAttribute_txtAttrContent_1']</value>
      <webElementGuid>d0f9fca2-66b4-45c3-bc8a-1b0857dae553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dOtherInfo']/table[2]/tbody/tr/td[2]/textarea</value>
      <webElementGuid>72797655-de3e-4fb0-8a8b-20acf9fb3335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td[2]/textarea</value>
      <webElementGuid>808133f9-9bc7-4f64-a025-1bd1e098ed52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'rptAttribute$ctl01$txtAttrContent' and @id = 'rptAttribute_txtAttrContent_1']</value>
      <webElementGuid>8f1c4aac-4514-4c60-b7de-ab9a2d4fe038</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
