<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CREDIT OFFICER</name>
   <tag></tag>
   <elementGuidId>5244128f-5f0c-4924-842b-22f4285628cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='rptAttribute_txtAttrContent_6']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rptAttribute_txtAttrContent_6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#rptAttribute_txtAttrContent_6</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>435fa266-0753-483e-b89e-e42bae003b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rptAttribute$ctl06$txtAttrContent</value>
      <webElementGuid>a61a0a4e-a649-46c5-9f49-a488a926c1a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>6c994df1-16b3-4d91-87f9-3d8d334c400e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>5d7473fe-9635-41d7-a028-ec7ffd31c83a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rptAttribute_txtAttrContent_6</value>
      <webElementGuid>d734ebf3-0bfd-40a9-b5d3-4ddcdb9aea79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtNotesStyle</value>
      <webElementGuid>dc3b301a-5545-4d9a-8ad0-859c42ace730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rptAttribute_txtAttrContent_6&quot;)</value>
      <webElementGuid>bff0d3f7-d2cf-477a-baee-fae2af67f2a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Other Data/iframe_Term  Condition_appForm</value>
      <webElementGuid>53a17d7f-da37-4171-ad30-542fea54e3db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='rptAttribute_txtAttrContent_6']</value>
      <webElementGuid>94f78eaf-a710-4562-bbdb-b196cbc2990a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dOtherInfo']/table[7]/tbody/tr/td[2]/textarea</value>
      <webElementGuid>a0b6c812-b414-435e-9678-c32cab08a824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[7]/tbody/tr/td[2]/textarea</value>
      <webElementGuid>73493645-5a96-4992-9e00-a427a9caef21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'rptAttribute$ctl06$txtAttrContent' and @id = 'rptAttribute_txtAttrContent_6']</value>
      <webElementGuid>5ee47912-6959-47f8-9de5-2ce94dbea59a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
