<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>INS Customer</name>
   <tag></tag>
   <elementGuidId>0c5f507e-eaf9-4dd8-9a6d-24f4a4ffd463</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucInsInit_rblInsAssetCoveredBy_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucInsInit_rblInsAssetCoveredBy_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>89f9fd5c-2dfe-4711-82e7-6e9e2aa666d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucInsInit_rblInsAssetCoveredBy_1</value>
      <webElementGuid>f7888c0d-a366-49df-81f8-0516e449dd63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>2882f57f-0f54-4ef8-8e78-f810e6cfeb4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucInsInit$rblInsAssetCoveredBy</value>
      <webElementGuid>b7349c8a-2eae-4d2c-8456-8591ff2a19b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>CU</value>
      <webElementGuid>a55bba4f-f997-4a6f-ad2d-dea024784b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ucInsInit$rblInsAssetCoveredBy$1\',\'\')', 0)</value>
      <webElementGuid>23ea1779-faee-4f38-bb49-69f9e7999d30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucInsInit_rblInsAssetCoveredBy_1&quot;)</value>
      <webElementGuid>113f5382-8734-46a4-8907-bd1cac2bb7c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Insurance Asset/iframe_Term  Condition_appForm (1)</value>
      <webElementGuid>e00d628a-cafe-4479-a0a7-ea3271c77053</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucInsInit_rblInsAssetCoveredBy_1']</value>
      <webElementGuid>73879450-21e4-48e5-97eb-ad256f97dcaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ucInsInit_rblInsAssetCoveredBy']/tbody/tr/td[2]/input</value>
      <webElementGuid>b1b6c990-3f3f-418b-8ed4-b78b47c94a29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>f595f880-93a5-4a5f-8c12-b5b1a6418bdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ucInsInit_rblInsAssetCoveredBy_1' and @type = 'radio' and @name = 'ucInsInit$rblInsAssetCoveredBy']</value>
      <webElementGuid>7811a4e2-46d9-4a41-8c3e-4dfe087470bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
