<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>INS Off System</name>
   <tag></tag>
   <elementGuidId>f6562100-f1ed-4fa4-abb5-a2691ce59a3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucInsInit_rblInsAssetCoveredBy_3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucInsInit_rblInsAssetCoveredBy_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c29e8a08-c4e1-41a5-bc57-777dad31f6f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucInsInit_rblInsAssetCoveredBy_3</value>
      <webElementGuid>44641a37-5cf4-4db5-9998-e1bcb1cee1a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>60ac3a6f-7f1b-4d2c-8ac9-9b850a78d8f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucInsInit$rblInsAssetCoveredBy</value>
      <webElementGuid>d3b4e95f-6397-424f-bc4f-8c2781a950f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>OF</value>
      <webElementGuid>9d3df495-8cc7-4322-9ac3-64a43418740e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ucInsInit$rblInsAssetCoveredBy$3\',\'\')', 0)</value>
      <webElementGuid>f9900584-2027-4669-bcd6-66e6a27418f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucInsInit_rblInsAssetCoveredBy_3&quot;)</value>
      <webElementGuid>b75eb6c2-6473-4c46-bcb6-525845943029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Insurance Asset/iframe_Term  Condition_appForm (1)</value>
      <webElementGuid>a6559ad2-06f2-47d0-98f2-ccf298090aab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucInsInit_rblInsAssetCoveredBy_3']</value>
      <webElementGuid>cf11dc2e-d55f-4e4a-98bb-a29cfac7cf8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ucInsInit_rblInsAssetCoveredBy']/tbody/tr/td[4]/input</value>
      <webElementGuid>c5077d51-aee2-4630-b9d7-1d8561f75783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/input</value>
      <webElementGuid>a6ad630a-ce7e-47cf-a028-731785caee90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ucInsInit_rblInsAssetCoveredBy_3' and @type = 'radio' and @name = 'ucInsInit$rblInsAssetCoveredBy']</value>
      <webElementGuid>7ae4b1aa-93eb-4e3d-9f34-3cca073aacf7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
