<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CEK NO 6</name>
   <tag></tag>
   <elementGuidId>1bce0e17-b5dc-4cba-8df4-a7caf1a1520c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvTermCondition_cbChecked_5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gvTermCondition_cbChecked_5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gvTermCondition_cbChecked_5</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>58e3114d-6aed-4dfe-8f12-71ccf71e28d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvTermCondition_cbChecked_5</value>
      <webElementGuid>2959ee14-bcdc-47cc-91ad-6455cade9324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>353f4bd7-89bb-45ee-ba3e-ee5ebea9ff66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvTermCondition$ctl07$cbChecked</value>
      <webElementGuid>b9b12268-1d49-4a79-8b6a-84d37c449045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'gvTermCondition$ctl07$cbChecked\',\'\')', 0)</value>
      <webElementGuid>d64b3b2d-2167-41e3-bfd3-88bc5af5afb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvTermCondition_cbChecked_5&quot;)</value>
      <webElementGuid>8aef8ce1-d808-4e14-806a-2a096bb57f53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Page_New Confins - Main/iframe_Term  Condition_appForm</value>
      <webElementGuid>c61d1ded-0694-458e-a26b-e685b60371f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvTermCondition_cbChecked_5']</value>
      <webElementGuid>d4386cfd-a838-4fa1-a485-08be0ee8001e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvTermCondition']/tbody/tr[7]/td[5]/input</value>
      <webElementGuid>4c7e9acf-1ff8-4080-8868-30abfb48aee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[5]/input</value>
      <webElementGuid>247611c7-aed8-4fe0-9270-8d78af75f793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'gvTermCondition_cbChecked_5' and @type = 'checkbox' and @name = 'gvTermCondition$ctl07$cbChecked']</value>
      <webElementGuid>41c3ded5-2074-4261-9b08-b34c52a691ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
