<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CEK NO 7</name>
   <tag></tag>
   <elementGuidId>385b2d4e-61eb-45aa-a599-6cf996a0dfee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvTermCondition_cbChecked_6']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gvTermCondition_cbChecked_6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gvTermCondition_cbChecked_6</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>95bccac1-a271-4997-af0e-46b321f495cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvTermCondition_cbChecked_6</value>
      <webElementGuid>ad9aef16-7993-4f7f-aa5c-fff49491daa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3a4d33cf-8855-4e27-a6de-c2303d35cbcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvTermCondition$ctl08$cbChecked</value>
      <webElementGuid>d5709e60-7223-4b03-af4a-ba73ec1d261c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'gvTermCondition$ctl08$cbChecked\',\'\')', 0)</value>
      <webElementGuid>2ece0cce-7e72-4af7-a8c9-cb3c8bb39465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvTermCondition_cbChecked_6&quot;)</value>
      <webElementGuid>e0f474d5-2704-4ac6-a4b4-c547703f3aff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Page_New Confins - Main/iframe_Term  Condition_appForm</value>
      <webElementGuid>1e61fed4-c79c-4389-96a9-cd03f5633ede</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvTermCondition_cbChecked_6']</value>
      <webElementGuid>6f5a3395-9be6-4846-8fa3-c6732408688b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvTermCondition']/tbody/tr[8]/td[5]/input</value>
      <webElementGuid>5f12cce1-2f06-42ca-8204-7e19e52bd44a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[5]/input</value>
      <webElementGuid>506f2d2c-31be-4e8f-9fb1-c1416bbbfe69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'gvTermCondition_cbChecked_6' and @type = 'checkbox' and @name = 'gvTermCondition$ctl08$cbChecked']</value>
      <webElementGuid>d5a465c0-2b14-4bd3-9629-7913e3de1613</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
