<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NO 6</name>
   <tag></tag>
   <elementGuidId>d887105d-b506-48ba-b005-060e3b7aa241</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='gvTermCondition_lblIsMandatory_5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gvTermCondition_lblIsMandatory_5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gvTermCondition_lblIsMandatory_5</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5c9038bb-ed6c-4725-82ed-27770e8094d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvTermCondition_lblIsMandatory_5</value>
      <webElementGuid>ac16539b-fd1a-43a6-8ac3-a8d2773f7ffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>e5cd61ee-e157-4bdc-826b-83494c260c77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvTermCondition_lblIsMandatory_5&quot;)</value>
      <webElementGuid>add9b287-12ec-4eac-88e8-784f2a6c7977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Page_New Confins - Main/iframe_Term  Condition_appForm</value>
      <webElementGuid>62b8eb15-1ec8-4637-bb6c-95b7dc5cb3fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='gvTermCondition_lblIsMandatory_5']</value>
      <webElementGuid>89670308-0a70-46ca-a66d-9e559b64e4a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvTermCondition']/tbody/tr[7]/td[4]/span</value>
      <webElementGuid>a1844b0c-bf28-4e1f-95c7-a98f1b1e7038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APP'])[6]/following::span[1]</value>
      <webElementGuid>696a6a3d-500d-457d-8539-2dd1d1edf5de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SURAT NIKAH'])[1]/following::span[2]</value>
      <webElementGuid>5c72ec36-e9da-4616-84d1-da1b124e6b07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invalid Date'])[11]/preceding::span[2]</value>
      <webElementGuid>1f83ac1e-4698-46ef-918c-a732290388ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This field is required'])[11]/preceding::span[3]</value>
      <webElementGuid>5f1b9bbf-56fb-4625-b75f-cd94e459664c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='No']/parent::*</value>
      <webElementGuid>8f01c281-58d6-4ce1-ad66-71959031701f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[4]/span</value>
      <webElementGuid>e22c1f4c-0774-450e-895a-87de4cd92927</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'gvTermCondition_lblIsMandatory_5' and (text() = 'No' or . = 'No')]</value>
      <webElementGuid>c9652fa5-7cd2-4fe4-88a9-1ec3b8a40dc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
