<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AmounttxtInput</name>
   <tag></tag>
   <elementGuidId>97135a4a-3ef4-45a6-8857-b51d6af69ecc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucINPPAmount_txtInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucINPPAmount_txtInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dc6e9ab4-a39f-4a00-897e-061c12cb3139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucINPPAmount$txtInput</value>
      <webElementGuid>14a9b1f8-5bb9-4c8a-bd50-2cdd522f7c7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bb1c45b8-a1ef-4461-9ded-ae9a9d43cc2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>89f3d503-e1b0-4334-9fb4-875990b1dfe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucINPPAmount_txtInput</value>
      <webElementGuid>b3669c72-ab9a-4782-8e4a-a403a5c42c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtAmountStyle</value>
      <webElementGuid>5d4cf9bd-f433-4752-ba26-e0b980e093db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>formatValue('ucINPPAmount_txtInput','ucINPPAmount_hdnInput','ucINPPAmount_txtInputDummy');</value>
      <webElementGuid>90615c3f-4168-4f6b-b3e7-e331428ba95c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clearFormatValue('ucINPPAmount_txtInput');</value>
      <webElementGuid>5c128b01-f5d4-41e2-b9f6-f7ef38b6cd3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return validateKey(event);</value>
      <webElementGuid>60f29db2-1386-4cf5-bf6d-5ecee1cce142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucINPPAmount_txtInput&quot;)</value>
      <webElementGuid>6c8317d1-3bcb-4adb-9e09-a842bd62d81a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Life Insurance/iframe_Term  Condition_appForm</value>
      <webElementGuid>814215a3-0ef6-41fc-bf59-b7e5b623cc9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucINPPAmount_txtInput']</value>
      <webElementGuid>8c00c132-6e29-4830-be32-affdd9bd714f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='trAmount']/td[2]/input[2]</value>
      <webElementGuid>4c4b9312-9546-4a04-b541-85db3a1cfc23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/input[2]</value>
      <webElementGuid>0c46c57d-29f7-42ee-8bc8-6d86fd250099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucINPPAmount$txtInput' and @type = 'text' and @id = 'ucINPPAmount_txtInput']</value>
      <webElementGuid>98b38312-29df-4ec5-8401-6190a6127039</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
