<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CalculatedBy Amount</name>
   <tag></tag>
   <elementGuidId>79dbdd19-3782-4e1d-af68-cd4e33be358c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rblCalculatedBy_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rblCalculatedBy_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5bcd0a8b-0490-4c33-87ef-d30e049ae0d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rblCalculatedBy_0</value>
      <webElementGuid>4a57b334-f435-4974-993e-c7b8ba471ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>0979c0e3-e33a-4018-9e36-9f7b5880b43f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rblCalculatedBy</value>
      <webElementGuid>428cbaaf-4dca-467e-937c-6d60dbb29362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>A</value>
      <webElementGuid>7e8602cb-49a2-469e-a0d2-e3239a444680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>a46cdd65-63aa-4c2b-a87e-2a957616bc73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rblCalculatedBy_0&quot;)</value>
      <webElementGuid>622a4dd0-147d-4242-8216-2c7e0dca4987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Life Insurance/iframe_Term  Condition_appForm</value>
      <webElementGuid>c3ac8c3c-bc40-4b9a-9cbf-3e0f17897b66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rblCalculatedBy_0']</value>
      <webElementGuid>415ef1f6-fdb4-4f96-9411-1eebd9ff676a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='rblCalculatedBy']/tbody/tr/td/input</value>
      <webElementGuid>053dfa57-c12d-449b-b6a9-6eee07f0dd72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>a3f3cf1e-6997-4913-8635-c57629df13ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'rblCalculatedBy_0' and @type = 'radio' and @name = 'rblCalculatedBy' and @checked = 'checked']</value>
      <webElementGuid>689283b9-e9d7-4456-9866-05820f3780fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
