<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CalculatedBy Persentage</name>
   <tag></tag>
   <elementGuidId>8cbd7f52-a7da-4449-a673-3b7cb1f6789b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rblCalculatedBy_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rblCalculatedBy_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7ee5d2a7-dd16-40fb-9afc-d9c6ec518934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rblCalculatedBy_1</value>
      <webElementGuid>547c4044-bbcc-4c51-bc18-cbc099a8efa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>a5bbe918-aed4-4863-af62-a0a4df3fd216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rblCalculatedBy</value>
      <webElementGuid>1af899fc-f2c7-4224-b590-9bfc1d150532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>P</value>
      <webElementGuid>381d9dd2-e471-4c5b-adfe-e88a8c311a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'rblCalculatedBy$1\',\'\')', 0)</value>
      <webElementGuid>ed6f4a05-0522-4371-a555-6f53c73e179b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rblCalculatedBy_1&quot;)</value>
      <webElementGuid>81ae9199-3878-4904-8cf6-c4da823a3c3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Life Insurance/iframe_Term  Condition_appForm</value>
      <webElementGuid>ab7ed9f3-ccb1-46ff-b9dc-e4dfb9a10e49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rblCalculatedBy_1']</value>
      <webElementGuid>1d237c12-64d0-44df-a792-f3daecbc561f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='rblCalculatedBy']/tbody/tr/td[2]/input</value>
      <webElementGuid>fdf7d9ae-f371-48a7-a43e-01051853e00c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>e02e14d1-4f10-40e3-8e69-0153a0b1214d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'rblCalculatedBy_1' and @type = 'radio' and @name = 'rblCalculatedBy']</value>
      <webElementGuid>74514a38-1cdc-40cc-904c-4690b25c89d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
