<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Cover Customer</name>
   <tag></tag>
   <elementGuidId>a6419fe8-c0de-4dbc-a398-f4c6248b2fb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cblCustomerInsured_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cblCustomerInsured_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7db10442-63f4-44fe-81c8-b928a0f68993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cblCustomerInsured_0</value>
      <webElementGuid>42407c18-fd22-4fe7-be78-166fe3670e5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ddc5fec8-07b2-45f1-a7d0-76d49a42bd39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cblCustomerInsured$0</value>
      <webElementGuid>9c9db9a7-cad0-4850-99ec-ce95b9c4418a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5830998</value>
      <webElementGuid>475e13db-2a8c-45ec-ad35-ef5108b89d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cblCustomerInsured_0&quot;)</value>
      <webElementGuid>42e7555e-2e35-4857-8092-27c25dffb009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Life Insurance/iframe_Term  Condition_appForm</value>
      <webElementGuid>13d57098-9211-43f2-b2b8-d06613d973eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cblCustomerInsured_0']</value>
      <webElementGuid>2204081b-9d70-4e07-950a-648f960b7c3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cblCustomerInsured']/tbody/tr/td/input</value>
      <webElementGuid>a64f2eed-f970-4d8e-bd16-3221e84b52b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr/td/input</value>
      <webElementGuid>c345da75-9a7e-4422-bd10-e344e94a0919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cblCustomerInsured_0' and @type = 'checkbox' and @name = 'cblCustomerInsured$0']</value>
      <webElementGuid>ee0a5f92-24d5-4972-a31d-9924d86c30c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
