<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Is Life</name>
   <tag></tag>
   <elementGuidId>3eb68bf2-15ad-48e9-bb33-d5d27deb82e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbIsCoverLifeIns</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cbIsCoverLifeIns']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>12fa39be-c5b1-4a00-ac49-b35e25a9f8b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbIsCoverLifeIns</value>
      <webElementGuid>4d759901-e7b5-40e8-9ecd-0c9258a83a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>fd575540-1598-4f4b-9c7c-3f20e12f7912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cbIsCoverLifeIns</value>
      <webElementGuid>d5e4724a-15c2-4f03-91f5-9af889d72662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'cbIsCoverLifeIns\',\'\')', 0)</value>
      <webElementGuid>7061c7d2-3513-422e-8613-e8399df17669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbIsCoverLifeIns&quot;)</value>
      <webElementGuid>78592833-fd22-4ba2-a200-b52038d13590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Life Insurance/iframe_Term  Condition_appForm</value>
      <webElementGuid>c3be54e4-f129-46d1-854a-e7b15456bfe0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cbIsCoverLifeIns']</value>
      <webElementGuid>713fc197-e82e-4cf7-b9c9-22786ba60630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divLifeInsInfo']/table/tbody/tr/td[2]/input</value>
      <webElementGuid>a911182e-1b3e-4735-aac8-eb36c5ce6326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>50b92556-8e98-4304-bfa5-8e8081375550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cbIsCoverLifeIns' and @type = 'checkbox' and @name = 'cbIsCoverLifeIns']</value>
      <webElementGuid>c73fc5e0-6f16-4605-a553-285deb7a27d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
