<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Notes</name>
   <tag></tag>
   <elementGuidId>eef42c36-9013-48bf-b044-1520367415f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt_LifeInsH_NewCoverNotes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='txt_LifeInsH_NewCoverNotes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>32cc195f-47c9-4042-9d31-929c4e206c92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_LifeInsH_NewCoverNotes</value>
      <webElementGuid>99e4807e-01b6-41c3-a72d-2dd7dbbb402d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>999be6b7-b15e-4b53-8946-45ec7aa8af3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>6d87e722-0f55-45cc-9d1b-8105c20591a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_LifeInsH_NewCoverNotes</value>
      <webElementGuid>20f9f3e9-1ba2-46e2-baf9-f9de53fef1e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtNotesStyle</value>
      <webElementGuid>c1122e58-f1aa-44d4-809c-7f61f4a46e9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_LifeInsH_NewCoverNotes&quot;)</value>
      <webElementGuid>408d6701-990e-48de-80fd-045474f22d13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Life Insurance/iframe_Term  Condition_appForm</value>
      <webElementGuid>e2192a03-3076-4532-ba6e-db8ad5ce50e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='txt_LifeInsH_NewCoverNotes']</value>
      <webElementGuid>592a86a9-10ad-468f-a45d-e4c7ba65c49c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divLifeInsInfo']/table/tbody/tr[5]/td[2]/textarea</value>
      <webElementGuid>837d664e-1e2e-4a90-88a6-9bb4035c33df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>39add35e-dbf8-4903-80be-749706cc70a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'txt_LifeInsH_NewCoverNotes' and @id = 'txt_LifeInsH_NewCoverNotes']</value>
      <webElementGuid>af3aab60-98c0-4c41-afda-f9bbd8a24a69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
