<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PercenttxtInput</name>
   <tag></tag>
   <elementGuidId>4d1d35a1-66df-4149-8f51-1b7946f56ad2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucINPPPercent_txtInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucINPPPercent_txtInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>377c3254-0ab1-4afe-917f-fcc3c96b2097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucINPPPercent$txtInput</value>
      <webElementGuid>65624077-c8e8-435e-9903-564b7d1ac800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ea9d54a8-5a27-4455-97e9-b0d806015736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>ece89b2c-71e7-42d1-bbba-f209e5e60d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucINPPPercent_txtInput</value>
      <webElementGuid>419b61ba-ac84-422e-8f47-cb870c3b1ad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtAmountStyle</value>
      <webElementGuid>11b6d760-c6c6-4542-b316-060f8737f3c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>formatValue('ucINPPPercent_txtInput','ucINPPPercent_hdnInput','ucINPPPercent_txtInputDummy');</value>
      <webElementGuid>5f3994ec-c005-4810-96ec-5f5aaafe9c9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clearFormatValue('ucINPPPercent_txtInput');</value>
      <webElementGuid>27a55cee-8512-4e4f-835e-83d37ee20770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return validateKey(event);</value>
      <webElementGuid>4ee09e7d-158d-4111-99e0-5b9bb5bdcdfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucINPPPercent_txtInput&quot;)</value>
      <webElementGuid>e968b0fc-e66e-41f5-afaa-02f8bb3dfae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Life Insurance/iframe_Term  Condition_appForm</value>
      <webElementGuid>63867f94-cbb8-476c-8590-fbb87ee559a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucINPPPercent_txtInput']</value>
      <webElementGuid>74ac629f-253d-46b3-b1ec-4b0dfd137eea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='trPercentage']/td[2]/input[2]</value>
      <webElementGuid>fb68bd72-1686-41b9-9a62-1d3494fd0c1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>e7b306bc-3d24-4a29-8c32-f17c66313a6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucINPPPercent$txtInput' and @type = 'text' and @id = 'ucINPPPercent_txtInput']</value>
      <webElementGuid>e7619f0d-4852-4cfd-b4a6-38a36ebb31a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
