<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SaveCont Life insurance</name>
   <tag></tag>
   <elementGuidId>77e72303-39bf-4e80-b534-b9c79fbd780a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lb_Form_SaveCont</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lb_Form_SaveCont']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8a19b24b-9473-4b95-94b8-b857a71943b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>2834d2a3-3324-4cb9-acc9-4f90e6013940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lb_Form_SaveCont</value>
      <webElementGuid>e58593c5-9846-4a71-90ac-65384302ee23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save &amp; Continue</value>
      <webElementGuid>a5f1be8f-8197-4850-abe4-8541bd818fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;lb_Form_SaveCont&quot;, &quot;&quot;, true, &quot;vgSave&quot;, &quot;&quot;, false, false))</value>
      <webElementGuid>5e5ad32d-4a87-4cdd-9863-39b26ac8823d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lb_Form_SaveCont</value>
      <webElementGuid>a8617bac-951b-441b-a2c4-81d9428f5371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnForm</value>
      <webElementGuid>5bb3f6e5-07bb-4b5f-bbcb-3ff46fa34aad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lb_Form_SaveCont&quot;)</value>
      <webElementGuid>3f940379-0854-466d-87b0-40c6f1e3dd2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Life Insurance/iframe_Term  Condition_appForm</value>
      <webElementGuid>c04e13fd-4583-43e7-9a98-b6ea8592f8c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lb_Form_SaveCont']</value>
      <webElementGuid>68376be0-2b30-4d91-9af9-9f138c326818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='btnFormContainer']/input</value>
      <webElementGuid>572bdd40-d2b2-422f-80ba-abb63a735839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d163875a-640d-4577-8274-ec002668aba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'lb_Form_SaveCont' and @id = 'lb_Form_SaveCont']</value>
      <webElementGuid>4fa63d10-e4cd-47bd-966b-37bb5ab5cf44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
