<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Cek BPKB</name>
   <tag></tag>
   <elementGuidId>276722cc-4836-4bb3-a321-208ece876f4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvAssetDocEdit_cbChecked_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvAssetDocEdit_cbChecked_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff6f1bca-c282-46f9-a86e-e0ec84d740ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvAssetDocEdit_cbChecked_0</value>
      <webElementGuid>f6c8145e-0783-4ef9-9c6d-00e735143db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5b92dc53-e27a-4dfc-abfb-aba8006e1571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvAssetDocEdit$ctl02$cbChecked</value>
      <webElementGuid>fc9140ef-8051-4c21-9320-3c5a0b4dd513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'gvAssetDocEdit$ctl02$cbChecked\',\'\')', 0)</value>
      <webElementGuid>3510b51f-a2e5-499e-8fef-6be55f773619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvAssetDocEdit_cbChecked_0&quot;)</value>
      <webElementGuid>32478196-cefd-492c-a93c-985d8aac2625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Asset/iframe_Term  Condition_appForm</value>
      <webElementGuid>9e05862f-221b-4381-9940-999cf14f0851</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvAssetDocEdit_cbChecked_0']</value>
      <webElementGuid>ca2b5406-7193-4af1-a133-b362d50a5922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvAssetDocEdit']/tbody/tr[2]/td[5]/input</value>
      <webElementGuid>6f80e870-1c77-4460-b730-8c1d8d404757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/input</value>
      <webElementGuid>6267aff0-f4c5-43ba-94a8-c27d9861a75e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'gvAssetDocEdit_cbChecked_0' and @type = 'checkbox' and @name = 'gvAssetDocEdit$ctl02$cbChecked']</value>
      <webElementGuid>91496d60-9f61-4890-9743-ac0180853b16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
