<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Cek NO FAKTUR</name>
   <tag></tag>
   <elementGuidId>ce2df95c-20ab-4da4-a240-c1f24eb24aca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvAssetDocEdit_cbChecked_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvAssetDocEdit_cbChecked_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>663e8063-13cf-47a2-b92b-1be595d35f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvAssetDocEdit_cbChecked_1</value>
      <webElementGuid>c64a08a6-763b-45cf-85ac-c88547bff4b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5efb0c9d-8eb5-4f81-90a4-0b935cd4ca1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvAssetDocEdit$ctl03$cbChecked</value>
      <webElementGuid>d1bcf2f9-e9c8-4d7a-b9b6-cbe225ee0930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'gvAssetDocEdit$ctl03$cbChecked\',\'\')', 0)</value>
      <webElementGuid>1b585ee9-e005-487b-8198-dbe860efc03d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvAssetDocEdit_cbChecked_1&quot;)</value>
      <webElementGuid>b2b3c26c-1b00-4dec-8176-40d06390d236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Asset/iframe_Term  Condition_appForm</value>
      <webElementGuid>14f76371-c3ab-4346-93d4-ca0be53a525b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvAssetDocEdit_cbChecked_1']</value>
      <webElementGuid>28d9b5a6-7ccb-4c76-9ffb-1b6b577d0025</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvAssetDocEdit']/tbody/tr[3]/td[5]/input</value>
      <webElementGuid>701e407b-72c0-4cff-b508-e5491323118d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[5]/input</value>
      <webElementGuid>1fdf699d-c08e-4b02-a261-c7ccfbbac491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'gvAssetDocEdit_cbChecked_1' and @type = 'checkbox' and @name = 'gvAssetDocEdit$ctl03$cbChecked']</value>
      <webElementGuid>3a0fd8ba-f68b-4a7c-878a-df71ba80abb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
