<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Cek BLOKIR BPKB</name>
   <tag></tag>
   <elementGuidId>da45cae6-37ad-454a-99d1-97e7192f6d90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvAssetDocEdit_cbChecked_3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvAssetDocEdit_cbChecked_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fcd344c2-28dc-4c7a-ba5d-cfc1c0c411e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvAssetDocEdit_cbChecked_3</value>
      <webElementGuid>3f3598c8-7cfd-45a8-adb1-76f4185d45e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ecf4425a-63ed-4693-a682-75ca7c10c9d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvAssetDocEdit$ctl05$cbChecked</value>
      <webElementGuid>baec6a31-39e3-4494-a8d0-fc841e0c040a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'gvAssetDocEdit$ctl05$cbChecked\',\'\')', 0)</value>
      <webElementGuid>06f4d4b4-6e10-4255-ad21-595bb672ace3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvAssetDocEdit_cbChecked_3&quot;)</value>
      <webElementGuid>2d507600-36e2-4f7c-8602-9a1faff960bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Asset/iframe_Term  Condition_appForm</value>
      <webElementGuid>7c41d4f0-fdb3-4aa6-a7f5-0eaf45e747dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvAssetDocEdit_cbChecked_3']</value>
      <webElementGuid>29237de1-2edf-497d-b062-10e525f1805e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvAssetDocEdit']/tbody/tr[5]/td[5]/input</value>
      <webElementGuid>62f086cf-ec98-4bd9-bf8d-04fe6462d5e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[5]/input</value>
      <webElementGuid>c110314d-1327-4ac2-b326-aa92a99ee5fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'gvAssetDocEdit_cbChecked_3' and @type = 'checkbox' and @name = 'gvAssetDocEdit$ctl05$cbChecked']</value>
      <webElementGuid>7a31c63a-266a-4859-885d-947b2cf9c68f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
