<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Doc No NO FAKKTUR</name>
   <tag></tag>
   <elementGuidId>ed96e46a-037f-4405-8133-d728d960c09b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvAssetDocEdit_txtDocNo_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvAssetDocEdit_txtDocNo_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dd07b9e5-9f59-43cd-89da-df8e4e1c723f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvAssetDocEdit$ctl03$txtDocNo</value>
      <webElementGuid>2f8b9a1b-e762-4c9b-ab40-205903eda566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4661ffdc-533f-46b2-bbf8-6c798a56a03c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvAssetDocEdit_txtDocNo_1</value>
      <webElementGuid>421b4947-7f30-4482-bfee-34f66b32b43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtInput</value>
      <webElementGuid>45c2ddc4-1033-47e6-ac09-c525fae17cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvAssetDocEdit_txtDocNo_1&quot;)</value>
      <webElementGuid>0176798a-1157-474e-afaf-4bdbda324285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Asset/iframe_Term  Condition_appForm</value>
      <webElementGuid>f1ac493b-5465-434e-96b9-6bcb21b9541b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvAssetDocEdit_txtDocNo_1']</value>
      <webElementGuid>e8d4d738-e0ac-475f-91d9-eb5e35f2df0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvAssetDocEdit']/tbody/tr[3]/td[6]/input</value>
      <webElementGuid>ebc410bc-04c9-4a34-8e41-09dd052749dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[6]/input</value>
      <webElementGuid>da46dfba-0561-4300-8678-4db944701862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'gvAssetDocEdit$ctl03$txtDocNo' and @type = 'text' and @id = 'gvAssetDocEdit_txtDocNo_1']</value>
      <webElementGuid>5475a4ab-4006-4051-82c5-d84326b13124</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
