<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Doc BPKB</name>
   <tag></tag>
   <elementGuidId>80624a1d-e6d5-4a71-8237-b1183f0bce69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvAssetDocEdit > tbody > tr:nth-of-type(2) > td:nth-of-type(3)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='gvAssetDocEdit']/tbody/tr[2]/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>08328936-8836-43e9-9a75-cf99cf32b12d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                    Yes
                                                </value>
      <webElementGuid>b40a3cc4-3d4f-4500-b65f-e95b15fc8588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvAssetDocEdit&quot;)/tbody[1]/tr[2]/td[3]</value>
      <webElementGuid>59bb8163-a7f3-49b0-87a1-7cb6f3c85d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Asset/iframe_Term  Condition_appForm</value>
      <webElementGuid>c1fcacea-e061-43ba-991a-80e81c61b9f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvAssetDocEdit']/tbody/tr[2]/td[3]</value>
      <webElementGuid>cfd5a8ca-bb1d-4e69-b8db-da599c99d2ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BPKB'])[1]/following::td[1]</value>
      <webElementGuid>a630f160-db53-4922-9449-7b3fb74de86e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOTE'])[1]/following::td[3]</value>
      <webElementGuid>d0da48f1-ebba-4311-adcd-f45c8975e2b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::td[1]</value>
      <webElementGuid>e3059b9d-cff1-40e6-b0e1-269548150fab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/table/tbody/tr[2]/td[3]</value>
      <webElementGuid>78231e1d-a026-4aae-b5b8-89b8b6970078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
                                                    Yes
                                                ' or . = '
                                                    Yes
                                                ')]</value>
      <webElementGuid>9b599c54-1185-4d63-84b6-efc12661c644</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
