<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Additional Admin Fee</name>
   <tag></tag>
   <elementGuidId>3563fcfb-897e-4843-a837-ca6492ef28b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucINAddAdminFeeAmt_txtInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucINAddAdminFeeAmt_txtInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ucINAddAdminFeeAmt_txtInput</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e4988160-c05c-4a67-9e31-e3e67c6d7ec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucINAddAdminFeeAmt$txtInput</value>
      <webElementGuid>64122b5d-bae9-476a-b22a-256fdef48a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>45fad134-6370-40c1-8350-84fcdaf2cd2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a21d50a3-dd3b-4277-9a26-5296e77065b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ucINAddAdminFeeAmt$txtInput\',\'\')', 0)</value>
      <webElementGuid>b14ba7f0-946c-492e-99a7-74ce431a74e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (WebForm_TextBoxKeyHandler(event) == false) return false;return validateKey(event);</value>
      <webElementGuid>13461288-2003-4305-b76e-3fdc7e24a9d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucINAddAdminFeeAmt_txtInput</value>
      <webElementGuid>65012f8c-09bc-4d84-aa8b-2d536ed3a4e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtAmountStyle</value>
      <webElementGuid>58741630-0e44-4a9d-86a4-09c92e87e53c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>formatValue('ucINAddAdminFeeAmt_txtInput','ucINAddAdminFeeAmt_hdnInput','ucINAddAdminFeeAmt_txtInputDummy');</value>
      <webElementGuid>44b34614-020c-4980-86c0-47d867eee707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clearFormatValue('ucINAddAdminFeeAmt_txtInput');</value>
      <webElementGuid>6a774845-07e7-4e46-8f54-f77099a83304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucINAddAdminFeeAmt_txtInput&quot;)</value>
      <webElementGuid>4d6f47f8-e09e-41e6-afed-f6291f094820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Financial Data/iframe_Term  Condition_appForm</value>
      <webElementGuid>27f2af52-7718-44c9-a0df-b4db987ac859</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucINAddAdminFeeAmt_txtInput']</value>
      <webElementGuid>8d3e2c04-7609-4c7b-b4bb-ef8b713418d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dFeesFinDataRegFixed']/table/tbody/tr[3]/td[2]/input[2]</value>
      <webElementGuid>dbf14d30-6dda-47c5-97f6-e2d22b26ec8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input[2]</value>
      <webElementGuid>0dd7b0f4-d1ce-4684-a4bb-763e66cc4c77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucINAddAdminFeeAmt$txtInput' and @type = 'text' and @id = 'ucINAddAdminFeeAmt_txtInput']</value>
      <webElementGuid>8a3112e6-f327-46b2-a0c2-b2feb9af73cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
