<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Admin Fee Amount</name>
   <tag></tag>
   <elementGuidId>b88bbd61-1bf6-46fa-915a-8c7b7eea50bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucINAdminFeeAmt_txtInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucINAdminFeeAmt_txtInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ucINAdminFeeAmt_txtInput</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>54d9ef53-790d-417c-ac59-57193e8b7701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucINAdminFeeAmt$txtInput</value>
      <webElementGuid>d33f1466-dc90-47a0-b5e6-87af5166a648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c66a376a-69ef-4354-8def-c9776e43a43a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5bfa6988-a0dc-46b1-b28b-0ccf0a1cfaff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ucINAdminFeeAmt$txtInput\',\'\')', 0)</value>
      <webElementGuid>330ff018-f247-4ecd-9cd4-3f57e756932b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (WebForm_TextBoxKeyHandler(event) == false) return false;return validateKey(event);</value>
      <webElementGuid>68185d7e-5be4-4443-89fe-7bb03ee0da69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucINAdminFeeAmt_txtInput</value>
      <webElementGuid>ce04a29a-bfb3-4f3a-84cc-75f50d0d79ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtAmountStyle</value>
      <webElementGuid>cce004d8-75dd-47b5-bc49-dcac20c74581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>formatValue('ucINAdminFeeAmt_txtInput','ucINAdminFeeAmt_hdnInput','ucINAdminFeeAmt_txtInputDummy');</value>
      <webElementGuid>23158c93-f5e7-4152-a287-a1451535dc20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clearFormatValue('ucINAdminFeeAmt_txtInput');</value>
      <webElementGuid>46976bd5-32b8-489e-ac71-535d2a7e5cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucINAdminFeeAmt_txtInput&quot;)</value>
      <webElementGuid>29933abd-1b14-4639-a224-e5c3db5bd487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Financial Data/iframe_Term  Condition_appForm</value>
      <webElementGuid>4aa9def7-e0c3-4b97-b528-d0a11e8aded5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucINAdminFeeAmt_txtInput']</value>
      <webElementGuid>43c9419f-f055-4518-af2c-cfcc6029a997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dFeesFinDataRegFixed']/table/tbody/tr/td[2]/input[2]</value>
      <webElementGuid>ffb48b4d-f8d5-4597-a313-43e75106a336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input[2]</value>
      <webElementGuid>ca0ee14e-667a-4362-9b0c-1e276132e342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucINAdminFeeAmt$txtInput' and @type = 'text' and @id = 'ucINAdminFeeAmt_txtInput']</value>
      <webElementGuid>ddb8099c-a002-49c5-80d2-d549ca0981fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
