<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CalculateFees</name>
   <tag></tag>
   <elementGuidId>41228506-ace4-413f-8733-ebe2bb30ae91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lbCalculateFees</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lbCalculateFees']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Calculate&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>98b02c75-865c-41bd-8d52-c952b450dd67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d415b0b6-e308-49b0-bfcb-767bd310de4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lbCalculateFees</value>
      <webElementGuid>b3dba259-17f9-4fac-967f-2a407af15ed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Calculate</value>
      <webElementGuid>c06a654a-d834-4f0b-a9c8-c1ff6fbfe201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;lbCalculateFees&quot;, &quot;&quot;, true, &quot;Fees&quot;, &quot;&quot;, false, false))</value>
      <webElementGuid>d26375a3-17dc-40cc-b50a-3fac0c63acfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lbCalculateFees</value>
      <webElementGuid>7e66f231-e339-4dea-9951-4d4562181d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnForm</value>
      <webElementGuid>abfd35ed-3bae-4d29-b708-150ada6db832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lbCalculateFees&quot;)</value>
      <webElementGuid>5f7d70aa-39f9-4316-987a-0e356d3205f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Financial Data/iframe_Term  Condition_appForm</value>
      <webElementGuid>e2fe8835-c43e-41eb-8781-9519ab6dc26e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lbCalculateFees']</value>
      <webElementGuid>797a1a89-8146-4f0b-9723-153842854eff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dFeesFinDataRegFixed']/div/input</value>
      <webElementGuid>12e6db88-80ee-450a-9dbf-f8d8fe1e4dc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/input</value>
      <webElementGuid>f954a466-db58-403a-a992-3077fc23b209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'lbCalculateFees' and @id = 'lbCalculateFees']</value>
      <webElementGuid>f38c6297-60d6-4833-b0cd-677dac2ffbae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
