<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Capitalize ddAminFee</name>
   <tag></tag>
   <elementGuidId>e5c6a5ee-5101-4bd0-b475-e1258380fd93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbAddAminFee</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cbAddAminFee']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;cbAddAminFee&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ffb000c4-de14-436e-aee7-85f5c8caf7f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbAddAminFee</value>
      <webElementGuid>10728ab0-19b5-4232-8fa0-4a9aca560edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ffdee731-2f79-4992-bba2-0514b234b558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cbAddAminFee</value>
      <webElementGuid>280325b9-235f-4d1e-8807-ae299d71a550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'cbAddAminFee\',\'\')', 0)</value>
      <webElementGuid>7552bce2-aabf-4fb7-bcfd-8434050dfe53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbAddAminFee&quot;)</value>
      <webElementGuid>33c3dde9-62e6-4211-998d-db2acfd7856a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Financial Data/iframe_Term  Condition_appForm</value>
      <webElementGuid>c7341566-c84c-4c86-a96a-55cae163d848</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cbAddAminFee']</value>
      <webElementGuid>e0a84f76-0958-4192-9e00-b39d2257eae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dFeesFinDataRegFixed']/table/tbody/tr[3]/td[2]/input[4]</value>
      <webElementGuid>a471fd53-17a4-4a1a-a419-88f6c80bae84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input[4]</value>
      <webElementGuid>9ada6c79-93a5-41b2-9332-7a301825660b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cbAddAminFee' and @type = 'checkbox' and @name = 'cbAddAminFee']</value>
      <webElementGuid>63e97ace-779d-4295-9436-97216316a81c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
