<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Capitalize FiduciaFeeAmt</name>
   <tag></tag>
   <elementGuidId>b55b5b8b-a9dd-4274-9974-3fb1c255d057</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbFiduciaFeeAmt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cbFiduciaFeeAmt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Fiducia Fee Amount Capitalize&quot;i] >> internal:label=&quot;Capitalize&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eddf0bea-b4f9-4d31-bc0e-e61c9c40ec75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbFiduciaFeeAmt</value>
      <webElementGuid>9cc070f5-d4d7-4e02-b6b0-f50d10baa9ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>cddeb0a4-2dc8-4b5e-b7f9-e5da42cd4a47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cbFiduciaFeeAmt</value>
      <webElementGuid>a52a825b-6933-469a-974d-4f8918f3d6dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'cbFiduciaFeeAmt\',\'\')', 0)</value>
      <webElementGuid>94da0e6c-9777-4002-b7fb-c676980dea04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbFiduciaFeeAmt&quot;)</value>
      <webElementGuid>85025b3b-e158-4f37-869f-a7ac4e2f0953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Financial Data/iframe_Term  Condition_appForm</value>
      <webElementGuid>1b3c462e-bc0c-4b25-b657-16091c01dbab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cbFiduciaFeeAmt']</value>
      <webElementGuid>d0c29da3-f068-46ad-aa2c-396cc739f6ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='trFiduciaAmt']/td[4]/input[4]</value>
      <webElementGuid>d407da05-7e1b-41ce-bc16-40b843badb4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[4]/input[4]</value>
      <webElementGuid>156bf558-354f-470f-b3e8-a3be8fdb4959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cbFiduciaFeeAmt' and @type = 'checkbox' and @name = 'cbFiduciaFeeAmt']</value>
      <webElementGuid>311cbd17-b99e-4e2d-8738-b2064a16000b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
