<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Capitalize ProvisionFee</name>
   <tag></tag>
   <elementGuidId>b07d61ef-a3df-4b2e-8219-dd65f3f115fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbProvisionFee</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cbProvisionFee']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cbProvisionFee</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0fdbb439-6db6-4895-b3b7-b6c08f0687a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbProvisionFee</value>
      <webElementGuid>9e7026ee-23b6-4d98-a6cd-02e0cc0ebb4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5ec2baa3-28a3-4f17-b4d2-75478664d45b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cbProvisionFee</value>
      <webElementGuid>5d4fbb1d-20d9-48c6-977c-c766784e7b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'cbProvisionFee\',\'\')', 0)</value>
      <webElementGuid>234bec01-cb9f-47e7-ac91-f5fb573d77be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbProvisionFee&quot;)</value>
      <webElementGuid>26e82a19-0587-44f2-a724-e5d8f918fc1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Financial Data/iframe_Term  Condition_appForm</value>
      <webElementGuid>f1bae179-a035-469f-8c0f-d29429b2dc45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cbProvisionFee']</value>
      <webElementGuid>83e504ae-2a62-4222-9dcd-5fa469d13de0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dFeesFinDataRegFixed']/table/tbody/tr[3]/td[4]/input[4]</value>
      <webElementGuid>60acdbad-78e2-4dab-bf4e-023603764d7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/input[4]</value>
      <webElementGuid>b6e651a7-e73e-49a7-bceb-6aaaa0c6ecd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cbProvisionFee' and @type = 'checkbox' and @name = 'cbProvisionFee']</value>
      <webElementGuid>20937a98-8403-4426-9c39-ca5d5dae03a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
