<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Capitalize AdminFeeAmt</name>
   <tag></tag>
   <elementGuidId>c063c4eb-96f3-4b37-8fb4-dbee4a1601bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbAdminFeeAmt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cbAdminFeeAmt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Admin Fee Amount Capitalize PROVISION FEE&quot;i] >> internal:label=&quot;Capitalize&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>497ca7b6-d47e-4f40-b256-abc345075e41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbAdminFeeAmt</value>
      <webElementGuid>11486e77-6a4b-4995-af14-dbf0245bdb99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ea87d91e-280c-4542-b438-52790862b20b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cbAdminFeeAmt</value>
      <webElementGuid>b741d581-d2ae-490e-8ab8-86ca9e7e0300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'cbAdminFeeAmt\',\'\')', 0)</value>
      <webElementGuid>fe1c1b11-f2e6-4110-875b-2f6f2a5ab8b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbAdminFeeAmt&quot;)</value>
      <webElementGuid>4533a7f6-5501-49c1-b677-adb3b5557072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Financial Data/iframe_Term  Condition_appForm</value>
      <webElementGuid>258874e6-d6f9-4f00-a1cf-5d9dab9fcfa9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cbAdminFeeAmt']</value>
      <webElementGuid>ebf4ee4b-a84f-4af5-83a5-115115233339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dFeesFinDataRegFixed']/table/tbody/tr/td[2]/input[4]</value>
      <webElementGuid>d085986f-54a5-4038-9b28-63a381f73baa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input[4]</value>
      <webElementGuid>7c81c753-05e6-4808-a5da-b487cd6114e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cbAdminFeeAmt' and @type = 'checkbox' and @name = 'cbAdminFeeAmt']</value>
      <webElementGuid>42fe1764-d63a-4561-9c57-2f6777a9044a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
