<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Capitalize NotaryFeeAmt</name>
   <tag></tag>
   <elementGuidId>0be477fc-1f14-4bcd-8aa3-e362dbb63385</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbNotaryFeeAmt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cbNotaryFeeAmt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Notary Amount Capitalize Provision Type Percentage Amount&quot;i] >> internal:label=&quot;Capitalize&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3fdcdc7e-c12c-4c8a-a8c9-7a929a0ec452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbNotaryFeeAmt</value>
      <webElementGuid>8cf4180f-3982-4f7b-a486-b88fcfa077fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>942bfe0c-4e75-4da1-bab2-e1543e7e592f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cbNotaryFeeAmt</value>
      <webElementGuid>8114bce4-aa89-4040-9d88-8ee2ab5aacd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'cbNotaryFeeAmt\',\'\')', 0)</value>
      <webElementGuid>b832cd38-c845-4b33-87f3-d36cf23c579c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbNotaryFeeAmt&quot;)</value>
      <webElementGuid>af276c79-d514-4b2c-9709-3b6a08ae3b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Financial Data/iframe_Term  Condition_appForm</value>
      <webElementGuid>44ef1f0c-5ee4-4b9c-b1f4-64aac99934e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cbNotaryFeeAmt']</value>
      <webElementGuid>eab8090f-bc55-43e3-8ac1-7db896307462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dFeesFinDataRegFixed']/table/tbody/tr[2]/td[2]/input[4]</value>
      <webElementGuid>8bba683b-0ab8-4eca-b4f6-fb2bbf7226bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input[4]</value>
      <webElementGuid>476134b9-3ca0-463e-83ed-7c7603652377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cbNotaryFeeAmt' and @type = 'checkbox' and @name = 'cbNotaryFeeAmt']</value>
      <webElementGuid>1fe7a2ea-6cb0-44b7-a507-61bfc28bf298</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
