<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Capitalize Survey</name>
   <tag></tag>
   <elementGuidId>08cba307-5457-49b3-b1b1-62331ce5907d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbSurvey</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cbSurvey']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Survey Fee Capitalize&quot;i] >> internal:label=&quot;Capitalize&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f160e7b1-c462-41a4-be77-a1efda486276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbSurvey</value>
      <webElementGuid>e4389964-cbe4-4840-ba8f-c55404dbd942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9f5c1ca2-9038-44f3-a047-d4c524faface</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cbSurvey</value>
      <webElementGuid>369a084a-2856-4204-9f21-658bdbd9d2fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'cbSurvey\',\'\')', 0)</value>
      <webElementGuid>42954d65-5f56-44b8-851e-b48fd8cb2cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbSurvey&quot;)</value>
      <webElementGuid>9f9b1183-72fd-4116-b537-f27aece93110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Financial Data/iframe_Term  Condition_appForm</value>
      <webElementGuid>f5d128ac-052b-42f9-898a-ce4b6df4e6c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cbSurvey']</value>
      <webElementGuid>9720a2c8-adfb-4852-9e1d-99e21d03ab7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dFeesFinDataRegFixed']/table/tbody/tr[5]/td[2]/input[4]</value>
      <webElementGuid>0b0aa003-d81e-4b49-9e5a-cd225e9b4e39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/input[4]</value>
      <webElementGuid>0d627c5f-70cb-4208-a441-34b87d216ce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cbSurvey' and @type = 'checkbox' and @name = 'cbSurvey']</value>
      <webElementGuid>8df8fe6f-c158-47ed-be19-f08327c932fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
