<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Capitalize Deduction Fee</name>
   <tag></tag>
   <elementGuidId>e2c9f76d-c104-4c9c-9bff-0f0f902e4819</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbOtherFeeAmt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cbOtherFeeAmt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Deduction Fee Capitalize Provision Percentage (%) %&quot;i] >> internal:label=&quot;Capitalize&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>67f356e3-7983-48d9-b60b-4d035c1a5330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbOtherFeeAmt</value>
      <webElementGuid>1494b88c-ae8d-4581-b377-1268fbf9fb17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e69b10a1-e9d2-4889-9619-2d0af896aa0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cbOtherFeeAmt</value>
      <webElementGuid>4339a935-1e49-4695-83a8-6ad3dba00cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'cbOtherFeeAmt\',\'\')', 0)</value>
      <webElementGuid>9350bf21-1d3e-48fa-b402-fa7fac828dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbOtherFeeAmt&quot;)</value>
      <webElementGuid>e93ad567-cc1d-4e53-b64d-bf0155a019e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Financial Data/iframe_Term  Condition_appForm</value>
      <webElementGuid>1af84363-e6be-4de7-baef-82c2a4ea46fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cbOtherFeeAmt']</value>
      <webElementGuid>dfc07698-ffc7-43c5-8040-41beb386f0ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dFeesFinDataRegFixed']/table/tbody/tr[4]/td[2]/input[4]</value>
      <webElementGuid>b3bb864e-7293-46f7-a4d6-a18faa784c23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/input[4]</value>
      <webElementGuid>2ef479c0-1774-4d0e-9d6b-edb5b4314172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cbOtherFeeAmt' and @type = 'checkbox' and @name = 'cbOtherFeeAmt']</value>
      <webElementGuid>ba706cbe-eadf-437c-a24b-5b94d04d6f56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
