<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Fiducia Fee Amount</name>
   <tag></tag>
   <elementGuidId>e38914ee-de11-4320-8159-2c6d26963f61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucINFiduciaFeeAmt_txtInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucINFiduciaFeeAmt_txtInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ucINFiduciaFeeAmt_txtInput</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>71b2b5b2-45b7-4711-987b-3e4431533b4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucINFiduciaFeeAmt$txtInput</value>
      <webElementGuid>a650c07b-4d5d-4aa2-8130-26fed69ca6aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d1cedce2-303c-424b-afb3-c9ef482f615b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>50,000.00</value>
      <webElementGuid>1fdadd77-712d-41b3-8951-b4881084770c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ucINFiduciaFeeAmt$txtInput\',\'\')', 0)</value>
      <webElementGuid>e2fc8f8d-ba86-4a7c-ab6d-300f4282bb27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (WebForm_TextBoxKeyHandler(event) == false) return false;return validateKey(event);</value>
      <webElementGuid>7b10b552-293b-4eae-92ce-b54d7d31c654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucINFiduciaFeeAmt_txtInput</value>
      <webElementGuid>42bd5a04-0cde-480b-8fb0-aa944e13b93d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtAmountStyle</value>
      <webElementGuid>9998a187-105c-455c-8a34-12ec24811ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>formatValue('ucINFiduciaFeeAmt_txtInput','ucINFiduciaFeeAmt_hdnInput','ucINFiduciaFeeAmt_txtInputDummy');</value>
      <webElementGuid>0bcf857d-5604-4e09-bb18-f64f006964c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clearFormatValue('ucINFiduciaFeeAmt_txtInput');</value>
      <webElementGuid>88684299-4f60-4667-b269-3174f5835c53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucINFiduciaFeeAmt_txtInput&quot;)</value>
      <webElementGuid>e4cc2799-9205-4572-b2a9-3ed97bc0fed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Financial Data/iframe_Term  Condition_appForm</value>
      <webElementGuid>39a77f3c-9613-4de4-856a-54b8f6830ec7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucINFiduciaFeeAmt_txtInput']</value>
      <webElementGuid>ea8fb88f-db79-4b91-aca3-096b70ed4df2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='trFiduciaAmt']/td[4]/input[2]</value>
      <webElementGuid>59f52add-bd79-4fea-85ae-c4ddf1e5d1d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[4]/input[2]</value>
      <webElementGuid>6a5e87da-91eb-4a92-b8f5-547d24bb6325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucINFiduciaFeeAmt$txtInput' and @type = 'text' and @id = 'ucINFiduciaFeeAmt_txtInput']</value>
      <webElementGuid>db770811-e3af-46d9-b471-9f94bd6d6a6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
