<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Fiducia Mandatory</name>
   <tag></tag>
   <elementGuidId>1f65519c-ef74-4e91-9d34-d92941280850</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rblFiduciaOption_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rblFiduciaOption_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Mandatory / Registered&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3054495b-5578-4b96-a9b0-2acdb4d40ac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rblFiduciaOption_0</value>
      <webElementGuid>1f105c2f-ba4a-43b7-95b8-a7e1af57b3b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>1c5c1135-bd75-4304-af20-cecc9c56589f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rblFiduciaOption</value>
      <webElementGuid>0b2f8457-165d-4197-8145-e5d6d0851f98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>M</value>
      <webElementGuid>75bf8dd9-2a07-406c-b1fd-a7e83fe44aaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>8bbf687a-0e4c-4499-af6f-9fec5e67e3ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rblFiduciaOption_0&quot;)</value>
      <webElementGuid>8eaac22c-9e29-4cb6-b72b-d4259de9f8d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Financial Data/iframe_Term  Condition_appForm</value>
      <webElementGuid>f9bfb697-ce16-4db6-ac51-c7034ff929f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rblFiduciaOption_0']</value>
      <webElementGuid>639675c8-182b-415c-9a60-2e798c89269f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='rblFiduciaOption']/tbody/tr/td/input</value>
      <webElementGuid>6d5528e4-7f6d-49e3-8fb7-7e27bcd880cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[4]/table/tbody/tr/td/input</value>
      <webElementGuid>39895e9d-3d52-4146-a18a-83b696746137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'rblFiduciaOption_0' and @type = 'radio' and @name = 'rblFiduciaOption' and @checked = 'checked']</value>
      <webElementGuid>ac20f715-3ca9-4e97-84d8-37627be86834</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
