<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Fiducia Optional</name>
   <tag></tag>
   <elementGuidId>af8d0d98-48b5-4b8c-899d-32b89e1bf31a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rblFiduciaOption_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rblFiduciaOption_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Optional / Not Registered&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8ff22e9a-e5ae-43c7-8991-1c5855d82f34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rblFiduciaOption_1</value>
      <webElementGuid>cdfa0c1e-110c-4612-bfa6-c88dec24a7c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ceb68ce5-cd55-43f4-b104-463fbe0a2bae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rblFiduciaOption</value>
      <webElementGuid>0d696f8b-8f9b-4268-8621-8faf034a91e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>O</value>
      <webElementGuid>f20b6491-deec-47f7-921e-1f9292a85e79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rblFiduciaOption_1&quot;)</value>
      <webElementGuid>2eb79e9a-6dc9-475c-ba03-bb6aa56ad57f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Financial Data/iframe_Term  Condition_appForm</value>
      <webElementGuid>55e276c8-2022-4caf-b778-1ba57c0bad36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rblFiduciaOption_1']</value>
      <webElementGuid>8f671fb3-11ed-4fd0-b06e-c81b32365fa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='rblFiduciaOption']/tbody/tr/td[2]/input</value>
      <webElementGuid>fb5f06db-8f8f-41e1-8db8-f6b9c5b4cc38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[4]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>07d4f153-5417-410c-82eb-895e7e635502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'rblFiduciaOption_1' and @type = 'radio' and @name = 'rblFiduciaOption']</value>
      <webElementGuid>d4cb2c0c-47fa-4a55-a747-1140ac1265c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
