<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Provision Percentage</name>
   <tag></tag>
   <elementGuidId>45457f9c-528e-40e4-9d6d-c8f08513021f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucINProvisionFeePrcnt_txtInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucINProvisionFeePrcnt_txtInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ucINProvisionFeePrcnt_txtInput</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7d2998ba-568a-49b2-b7c0-1b4bf4ec46a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucINProvisionFeePrcnt$txtInput</value>
      <webElementGuid>a32c7881-f5bd-4934-bfff-2755edbbba76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1f503784-178d-4111-bbe9-961b6ad8198a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8c7d177f-58ca-4a7c-a49b-e77685787226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ucINProvisionFeePrcnt$txtInput\',\'\')', 0)</value>
      <webElementGuid>e6d4f7a9-a275-4d7c-82c6-f467a68aebc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (WebForm_TextBoxKeyHandler(event) == false) return false;</value>
      <webElementGuid>bcd5f1f3-c6c8-4e7c-b9a7-d134cb36f1e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucINProvisionFeePrcnt_txtInput</value>
      <webElementGuid>8ef773dd-ac0b-4254-b2a1-4ea86e87237c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtMedPercentageStyle</value>
      <webElementGuid>9daf4dd6-f170-4314-aebd-3a241ea0abdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>formatValuePercent('ucINProvisionFeePrcnt_txtInput','ucINProvisionFeePrcnt_hdnInput','ucINProvisionFeePrcnt_txtInputDummy');</value>
      <webElementGuid>8e0a2cd2-aaed-4cf2-9cc1-71db8ae8e442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clearFormatValue('ucINProvisionFeePrcnt_txtInput');</value>
      <webElementGuid>f3914935-9d4f-4ddd-86f2-8736666dbba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucINProvisionFeePrcnt_txtInput&quot;)</value>
      <webElementGuid>eb4268be-4a98-4afb-9576-a0d4d67765e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Financial Data/iframe_Term  Condition_appForm</value>
      <webElementGuid>f9b141a8-7b4d-4a09-a16f-ed9ea9732961</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucINProvisionFeePrcnt_txtInput']</value>
      <webElementGuid>f3f701ba-a102-4af5-912f-e669d7600836</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dFeesFinDataRegFixed']/table/tbody/tr[4]/td[4]/input[2]</value>
      <webElementGuid>2df56e64-5b2b-41f9-b953-826a94d0bc6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[4]/input[2]</value>
      <webElementGuid>ff60916a-cefd-4fa1-91a5-08a23f8a2c78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucINProvisionFeePrcnt$txtInput' and @type = 'text' and @id = 'ucINProvisionFeePrcnt_txtInput']</value>
      <webElementGuid>0b6932a5-ca99-43d7-a11d-ef6aacf474ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
