<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Notary Amount</name>
   <tag></tag>
   <elementGuidId>e81fa204-22c6-4a10-b299-12bd235ef607</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucINNotaryFeeAmt_txtInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucINNotaryFeeAmt_txtInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ucINNotaryFeeAmt_txtInput</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6efd6227-f3d6-4525-b890-10a3f5a80940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucINNotaryFeeAmt$txtInput</value>
      <webElementGuid>1a0a9405-911c-4a4e-9e19-1a0141523cf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2676e996-a870-45db-b2b3-be64018827d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b6d5bf31-dc71-4c5f-ab9d-d4f698d285a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ucINNotaryFeeAmt$txtInput\',\'\')', 0)</value>
      <webElementGuid>64b9c888-2856-43f8-8bb3-53945fb33cfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (WebForm_TextBoxKeyHandler(event) == false) return false;return validateKey(event);</value>
      <webElementGuid>f725520c-5f9c-4604-b901-49ab0511a7ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucINNotaryFeeAmt_txtInput</value>
      <webElementGuid>ba84b36b-2998-48ad-bb72-fa9dcec371d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtAmountStyle</value>
      <webElementGuid>a6bb9042-2bb8-4684-9243-570148755c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>formatValue('ucINNotaryFeeAmt_txtInput','ucINNotaryFeeAmt_hdnInput','ucINNotaryFeeAmt_txtInputDummy');</value>
      <webElementGuid>4de36a83-9b9c-4c92-8040-c7be4bc9d253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clearFormatValue('ucINNotaryFeeAmt_txtInput');</value>
      <webElementGuid>fe9f1cb1-ae20-4e5d-bc02-bb15e9ae5a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucINNotaryFeeAmt_txtInput&quot;)</value>
      <webElementGuid>a4b2b4e0-8e54-435a-a433-2de8779061e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Financial Data/iframe_Term  Condition_appForm</value>
      <webElementGuid>d8ed3dd8-6826-4d6f-94b1-8abc6bb68477</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucINNotaryFeeAmt_txtInput']</value>
      <webElementGuid>b927d533-4f04-4bdf-b6af-674721134da4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dFeesFinDataRegFixed']/table/tbody/tr[2]/td[2]/input[2]</value>
      <webElementGuid>2b53bf74-334e-4cb5-8939-caee7b6c4f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input[2]</value>
      <webElementGuid>98d2d672-8195-426b-bee5-ed9fd027f6a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucINNotaryFeeAmt$txtInput' and @type = 'text' and @id = 'ucINNotaryFeeAmt_txtInput']</value>
      <webElementGuid>5a050bba-fe63-4a8a-be88-757fee606f4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
