<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Provision Amount</name>
   <tag></tag>
   <elementGuidId>c9529841-08d4-4c9d-93a4-2c8fa606c196</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rblProvisionType_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rblProvisionType_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Amount&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>565598bc-c2dc-469f-b2e4-4bb11eefa2a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rblProvisionType_1</value>
      <webElementGuid>7a807c71-2105-4bb2-a209-aa7388afb582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>98074562-f085-46c6-9fe3-aa423e24cd65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rblProvisionType</value>
      <webElementGuid>28cd1c58-a523-426b-90d3-17e8653fec47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>AMT</value>
      <webElementGuid>75dfc931-0188-4a45-85ff-497b61406f35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'rblProvisionType$1\',\'\')', 0)</value>
      <webElementGuid>e5e85246-75dd-423b-a148-e01ee1f2e2a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rblProvisionType_1&quot;)</value>
      <webElementGuid>7eb14849-75b9-4f22-9340-ecd6f48679b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Financial Data/iframe_Term  Condition_appForm</value>
      <webElementGuid>aef8c25f-0f8e-4d02-bfeb-341367cdc440</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rblProvisionType_1']</value>
      <webElementGuid>51b6bf73-9ebd-431b-8441-2b2c1ddf3f7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='rblProvisionType']/tbody/tr/td[2]/input</value>
      <webElementGuid>4ddba1bc-6793-44b2-bcc9-f32d7b00ef94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>77536931-3178-4a58-9dec-b5ee5aeb2edc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'rblProvisionType_1' and @type = 'radio' and @name = 'rblProvisionType']</value>
      <webElementGuid>23326d44-f251-4d57-b8aa-e08bbd38feca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
