<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Provision Persen</name>
   <tag></tag>
   <elementGuidId>9c719031-7e72-4cdd-b3e2-2ec84fad11e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rblProvisionType_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rblProvisionType_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Percentage&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b7827cb0-2582-4b43-b545-ee2cdbb22d0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rblProvisionType_0</value>
      <webElementGuid>58e540cd-da5d-42d7-9897-6fcb3f8706c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>d74a722c-3e5d-4161-b246-0954a44df630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rblProvisionType</value>
      <webElementGuid>f2b31e38-3fd1-4dd9-b70e-03daaaad4438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>PRCNT</value>
      <webElementGuid>12142109-d025-4a37-94e9-8e1196ff8195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>73ac7c7f-c751-4a7a-9ea5-2013771b0852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rblProvisionType_0&quot;)</value>
      <webElementGuid>14794dd0-c2cc-42e4-b958-7e2c3005ef51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Financial Data/iframe_Term  Condition_appForm</value>
      <webElementGuid>33ba1eb2-a43e-45e5-9b7b-d5d705bf4072</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rblProvisionType_0']</value>
      <webElementGuid>20c60cea-be24-42ed-9c1c-3e0eae6cbe64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='rblProvisionType']/tbody/tr/td/input</value>
      <webElementGuid>8f6ebd2c-9252-4772-a4bb-023c01f092e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/table/tbody/tr/td/input</value>
      <webElementGuid>cefac0c1-05dc-4da5-8522-a594a6e6fc76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'rblProvisionType_0' and @type = 'radio' and @name = 'rblProvisionType' and @checked = 'checked']</value>
      <webElementGuid>963cb544-e1a8-4097-abe1-dfdcd22a26e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
