<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Rate</name>
   <tag></tag>
   <elementGuidId>563ffc5e-6e16-49e0-99c7-27b61aa9d504</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucINRate_txtInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucINRate_txtInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ucINRate_txtInput</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b829a18-6982-4833-b0cf-8c2256c15b00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucINRate$txtInput</value>
      <webElementGuid>e4b08320-c88d-490b-b7d5-3d9db7dad515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5188ebaa-9cf0-4780-bf2f-ffb9f853c98d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0.000000</value>
      <webElementGuid>c10b73d0-1ac2-4c7f-96b0-f9d0a5e9b2bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucINRate_txtInput</value>
      <webElementGuid>d00f0db1-3bf5-420c-8ef4-f54c507059eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtMedPercentageStyle</value>
      <webElementGuid>d43f9188-ea57-4c66-8aee-325d734a2fe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clearFormatValue('ucINRate_txtInput');</value>
      <webElementGuid>3af0e9b1-e018-4604-b916-ff0fcdd1238e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>formatValuePercent('ucINRate_txtInput','ucINRate_hdnInput','ucINRate_txtInputDummy');</value>
      <webElementGuid>b8e4105e-2076-4a67-95cc-c705557a52e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucINRate_txtInput&quot;)</value>
      <webElementGuid>a5ed0b03-4466-4d4a-b590-40104f3b0c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Financial Data/iframe_Term  Condition_appForm</value>
      <webElementGuid>d4d66676-ed49-41a1-bbbf-508917269761</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucINRate_txtInput']</value>
      <webElementGuid>328d1c31-2a4b-4f6d-8d07-fd75ae5b4caa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dFinDataRegFixed']/table/tbody/tr[9]/td[2]/input[2]</value>
      <webElementGuid>d8c1e0ba-c1ce-46d8-9170-dea07bc95567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td[2]/input[2]</value>
      <webElementGuid>68fd307e-06f2-43cd-89d6-b524696dbed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucINRate$txtInput' and @type = 'text' and @id = 'ucINRate_txtInput']</value>
      <webElementGuid>11b291c4-3e5b-4eb0-b697-90d56d3ae2a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
