<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Survey Fee</name>
   <tag></tag>
   <elementGuidId>652a7e12-90ce-4270-9d31-222ca685b68d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucINSurveyFeeAmt_txtInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucINSurveyFeeAmt_txtInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ucINSurveyFeeAmt_txtInput</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>875c8e6d-17c7-4bb8-a806-66c3cf0aba30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucINSurveyFeeAmt$txtInput</value>
      <webElementGuid>838f4d7c-8694-4dbf-ad98-81951098db7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f1b08f6c-733c-4576-b169-b588320bcbcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>081b01d9-e286-498a-ba09-45ac23a18f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ucINSurveyFeeAmt$txtInput\',\'\')', 0)</value>
      <webElementGuid>d6045677-bfb7-4554-8267-1e2e33f1b63a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (WebForm_TextBoxKeyHandler(event) == false) return false;return validateKey(event);</value>
      <webElementGuid>084426e4-8ac3-4b4b-adc5-5ebc51f6bcfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucINSurveyFeeAmt_txtInput</value>
      <webElementGuid>344e6341-ccfa-41c7-be75-95729ac83bd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtAmountStyle</value>
      <webElementGuid>2d808d2f-d5fe-45ba-b8b2-d74ae7163862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>formatValue('ucINSurveyFeeAmt_txtInput','ucINSurveyFeeAmt_hdnInput','ucINSurveyFeeAmt_txtInputDummy');</value>
      <webElementGuid>0f076d81-636f-4f04-8d56-48557cfb67ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clearFormatValue('ucINSurveyFeeAmt_txtInput');</value>
      <webElementGuid>7f6c371b-b152-4087-a0a3-4f87b8884cbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucINSurveyFeeAmt_txtInput&quot;)</value>
      <webElementGuid>f65c65dc-8080-4e46-815a-2b5a0edf3c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Financial Data/iframe_Term  Condition_appForm</value>
      <webElementGuid>f000660a-9b18-4403-a45d-c6245aecc696</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucINSurveyFeeAmt_txtInput']</value>
      <webElementGuid>dc4f6b56-fff5-459c-abe8-4e5b5aa95a9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dFeesFinDataRegFixed']/table/tbody/tr[5]/td[2]/input[2]</value>
      <webElementGuid>9dcd09d2-ebdc-43fb-9949-2cb618d0653b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/input[2]</value>
      <webElementGuid>b6419e1c-4b23-4278-876a-d41a8501f44e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucINSurveyFeeAmt$txtInput' and @type = 'text' and @id = 'ucINSurveyFeeAmt_txtInput']</value>
      <webElementGuid>550689e7-6278-4a51-8b1f-ed6a7751ecac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
